(()=>{'use strict';
let S=null,raf=0,startedAt=0,pausedAt=0,pausedAccum=0,motion=true,speed=1,activeMirror=0,lastPoints=new Map(),interglassUnsub=null,creationTrail=[];
const $=id=>document.getElementById(id);
const short=(v,n=14)=>v?String(v).slice(0,n)+'…':'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const edgeColor={TYPED_COMPATIBILITY:'#5ee7ff',ANALOGY:'#b89aff',CONTRAST:'#ffc86b',REPULSION:'#ff728f',BOUNDARY:'#70a8ff',UNRESOLVED_NEIGHBOURHOOD:'#8fa4bc',MULTI_HOP_CONTACT_MEMORY:'#7df6be'};
const atomColor={STATE:'#5ee7ff',CONDITION:'#7df6be',TRANSFORMATION:'#b89aff',CONTROL_FLOW:'#70a8ff',TYPE:'#ff9fd0',INTERFACE:'#ffc86b',EFFECT:'#ff728f',DEPENDENCY:'#9ad1ff',VERIFICATION:'#d7ff8a',FAILURE:'#ff8c71',REPRESENTATION:'#edf5ff'};
const debug=window.__GRAMMAR_GLASS_VISUAL_STATE__={loaded:false,frameCount:0,motionEnabled:true,activeMirrorIndex:0,lastFrameAt:0,directCarryCount:0,multiHopPathCount:0,evidenceAtomCount:0,renderedAtomCount:0,projectionHeldAtomCount:0,fullEvidenceRetained:true,visualInterpolationCreatesEvidence:false,projectionBudgetCreatesEvidence:false,interglassState:'EMPTY',runAttemptCount:0,lastRuntimeReceipt:null,lastRuntimePayloadDigest:null,innerGlassExecutor:'DISPOSABLE_BROWSER_SANDBOX'};

function valid(x){return x&&x.schema==='axm.code.grammar-glass-visual-snapshot.v1'&&x.cycle&&Array.isArray(x.cycle.atoms)&&Array.isArray(x.cycle.edges)&&Array.isArray(x.draftSky)}
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function visualElapsed(now){if(!startedAt)return 0;const frozen=motion?0:Math.max(0,now-pausedAt);return Math.max(0,(now-startedAt-pausedAccum-frozen)/1000)}
function livePoint(a,w,h,elapsed){const scale=Math.min(w,h)*.42;const visualTicksPerSecond=18;const velocity=Number(a.angularVelocityPpm||0)+Number(a.appliedInfluenceCarryPpm||0)*.35;const deltaTurns=(velocity/1000000)*visualTicksPerSecond*elapsed*speed;const angle=Number(a.position?.angle||0)+deltaTurns*Math.PI*2;const twist=Math.sin(elapsed*1.15+Number(a.orbitBand||0)*.72)*.008;const radius=Math.max(.1,Number(a.position?.radius||.6)+twist);return{x:w/2+Math.cos(angle)*radius*scale,y:h/2+Math.sin(angle)*radius*scale,angle,radius}}
function line(ctx,a,b,color,width,d,alpha=.4,dash=[]){ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.lineWidth=width*d;ctx.setLineDash(dash.map(v=>v*d));ctx.stroke();ctx.restore()}
function pulse(ctx,a,b,t,color,d,r=2.6){const x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;ctx.save();ctx.beginPath();ctx.arc(x,y,r*d,0,Math.PI*2);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=10*d;ctx.fill();ctx.restore()}
function pulsePolyline(ctx,points,t,color,d){if(points.length<2)return;const lengths=[];let total=0;for(let i=0;i<points.length-1;i++){const dx=points[i+1].x-points[i].x,dy=points[i+1].y-points[i].y,l=Math.hypot(dx,dy);lengths.push(l);total+=l}let target=t*total,acc=0;for(let i=0;i<lengths.length;i++){if(target<=acc+lengths[i]||i===lengths.length-1){const local=lengths[i]?Math.max(0,Math.min(1,(target-acc)/lengths[i])):0;pulse(ctx,points[i],points[i+1],local,color,d,3.2);return}acc+=lengths[i]}}
function drawToroid(ctx,w,h,d,elapsed){ctx.save();ctx.translate(w/2,h/2);for(let i=0;i<12;i++){const phase=elapsed*.08*(i%2?1:-1);ctx.beginPath();ctx.ellipse(0,0,(.22+i*.033)*Math.min(w,h),(.10+i*.015)*Math.min(w,h),phase,0,Math.PI*2);ctx.strokeStyle=i%3===0?'#5ee7ff22':'#b89aff12';ctx.lineWidth=.8*d;ctx.stroke()}ctx.restore()}
function visualAtomEntries(){const api=window.AXMGrammarGlassRenderBudget;return api&&api.getAtomEntries?api.getAtomEntries():S.cycle.atoms.map((atom,index)=>({atom,index}))}
function drawField(now){if(!S)return;const c=$('field'),[w,h,d]=fit(c),ctx=c.getContext('2d'),elapsed=visualElapsed(now),entries=visualAtomEntries();ctx.clearRect(0,0,w,h);drawToroid(ctx,w,h,d,elapsed);lastPoints=new Map();for(const {atom:a} of entries)lastPoints.set(a.atomId,livePoint(a,w,h,elapsed));
for(const e of S.cycle.edges){const a=lastPoints.get(e.leftAtomId),b=lastPoints.get(e.rightAtomId);if(!a||!b)continue;line(ctx,a,b,edgeColor[e.connectionClass]||'#8fa4bc',e.thresholdMet?1.05:.55,d,e.thresholdMet?.35:.16,e.crossGrammar?[2,4]:[])}
const direct=(S.cycle.influenceCarries||[]).filter(v=>Number(v.signedDeltaPpm)!==0).slice(0,80);direct.forEach((v,i)=>{const a=lastPoints.get(v.sourceAtomId),b=lastPoints.get(v.targetAtomId);if(!a||!b)return;line(ctx,a,b,'#7df6be',1.05,d,.25,v.crossGrammar?[2,4]:[]);const t=(elapsed*.38+i*.071)%1;pulse(ctx,a,b,t,'#7df6be',d,2.4)});
const paths=(S.contactMemory?.multiHopPaths||[]).slice(0,28);paths.forEach((path,i)=>{const points=path.pathAtomIds.map(id=>lastPoints.get(id)).filter(Boolean);if(points.length<2)return;for(let j=0;j<points.length-1;j++)line(ctx,points[j],points[j+1],'#b89aff',1,d,.24,[5,5]);pulsePolyline(ctx,points,(elapsed*.23+i*.053)%1,'#b89aff',d)});
for(const {atom:a} of entries){const p=lastPoints.get(a.atomId);if(!p)continue;const influenced=Number(a.appliedInfluenceCarryCount||0)>0;ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,(influenced?2.25:1.45)*d,0,Math.PI*2);ctx.fillStyle=atomColor[a.atomType]||'#fff';ctx.globalAlpha=influenced?.94:.72;if(influenced){ctx.shadowColor=atomColor[a.atomType]||'#fff';ctx.shadowBlur=6*d}ctx.fill();ctx.restore()}
debug.frameCount++;debug.lastFrameAt=now;debug.motionEnabled=motion;debug.directCarryCount=direct.length;debug.multiHopPathCount=paths.length;debug.evidenceAtomCount=S.cycle.atoms.length;debug.renderedAtomCount=entries.length;debug.projectionHeldAtomCount=Math.max(0,S.cycle.atoms.length-entries.length)}
function frame(now){drawField(now);raf=requestAnimationFrame(frame)}
function startMotion(){cancelAnimationFrame(raf);startedAt=performance.now();pausedAt=0;pausedAccum=0;debug.frameCount=0;raf=requestAnimationFrame(frame)}

function drawSky(){if(!S)return;const c=$('sky'),[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);for(const st of S.draftSky){const px=w/2+Number(st.x||0)*w*.43,py=h/2+Number(st.y||0)*h*.42,r=(2+5*Number(st.brightness||0))*d;ctx.save();ctx.beginPath();ctx.arc(px,py,r,0,Math.PI*2);ctx.fillStyle='#edf5ff';ctx.shadowColor='#b89aff';ctx.shadowBlur=10*d;ctx.fill();ctx.restore()}}
function inspect(v){$('inspector').textContent=JSON.stringify(v,null,2)}
function whyForFormation(sha){return(S.formationWhy||[]).find(w=>w.formationSha256===sha)||null}
function responseForMirror(index){const mirror=(S.mirrors||[])[index];if(!mirror)return null;return(S.mirrorResponses||[]).find(r=>r.mirrorObservationSha256===mirror.mirrorObservationSha256)||(S.mirrorResponses||[])[index]||null}
function renderWhy(why){const root=$('why');if(!why){root.innerHTML='<div class="muted">No derivation explanation recorded for this observation.</div>';return}root.innerHTML=(why.whySteps||[]).map(step=>`<div class="why-step"><b>${esc(step.code)}</b><span>${esc(step.detail)}</span></div>`).join('')+`<div class="truth">explanation ${esc(short(why.explanationSha256,20))} · simulator derivation only</div>`}
function trail(state,detail=''){creationTrail.push({sequence:creationTrail.length+1,state,detail:String(detail||'')});if(creationTrail.length>24)creationTrail.shift();const root=$('runTrail');if(root)root.innerHTML=creationTrail.map(item=>`<div class="trail-event"><span>${item.sequence}</span><b>${esc(item.state)}</b><small>${esc(item.detail)}</small></div>`).join('')}
function setInterglassState(state,detail=''){debug.interglassState=state;const label=$('sandboxState');if(label)label.textContent=state;const capsule=$('sandboxCapsuleState');if(capsule)capsule.textContent=state;const orb=$('candidateOrb');if(orb)orb.dataset.state=state;trail(state,detail)}
function renderInterglass(){const I=S&&S.interglass;if(interglassUnsub){interglassUnsub();interglassUnsub=null}creationTrail=[];const info=$('candidateInfo'),arm=$('armCandidate'),run=$('runCandidate'),release=$('releasePayload'),frame=$('sandboxFrame');if(!I||!I.candidateModel||!I.runRequest){info&&(info.textContent='No Interglass candidate in this snapshot.');arm&&(arm.disabled=true);run&&(run.disabled=true);release&&(release.disabled=true);setInterglassState('EMPTY','No runnable candidate recorded');return}const model=I.candidateModel,req=I.runRequest;info.textContent=[`candidate ${short(model.candidateModelDigest,24)}`,`seed ${short(model.candidateSeed,24)}`,`grammars ${(model.languageIds||[]).join(' × ')}`,`cells ${(model.cells||[]).length}`,`expected ${short(req.expectedResultDigest,24)}`,`executor ${req.executorProfile?.enforcementClass||'HELD'}`,`network ${req.executorProfile?.networkMode||'NONE'}`,`attempt ceiling ${req.resourceCeilings?.maxAttempts||1}`].join('\n');setInterglassState(req.result==='EXECUTION_HELD_NO_ADAPTER'?'EXECUTION_HELD_NO_ADAPTER':'CANDIDATE_RECEIVED',req.result);run.disabled=true;release.disabled=true;arm.disabled=req.result!=='INTERGLASS_EXECUTION_REQUEST_READY_NOT_EXECUTED';interglassUnsub=window.AXMInterglassExecutor.on(event=>{setInterglassState(event.state,event.detail&&event.detail.reason||event.detail&&event.detail.requestSha256||'');if(event.state==='EXECUTION_READY'){run.disabled=false;arm.disabled=true}if(event.state==='RUNNING'){run.disabled=true;debug.runAttemptCount=1}if(['PASS_OBSERVED','FAIL_OBSERVED','CRASH_OBSERVED','TIMEOUT_OBSERVED'].includes(event.state)){const receipt=event.detail&&event.detail.receipt;debug.lastRuntimeReceipt=receipt||null;debug.lastRuntimePayloadDigest=receipt&&receipt.runtimePayloadDigest||null;release.disabled=false;if(receipt)inspect({interglassRuntimeReceipt:receipt,truth:'Browser runtime observation only; pass is not correctness, admission, selection or promotion.'})}if(event.state==='RESULT_SEALED'&&event.detail&&event.detail.released){release.disabled=true}});arm.onclick=async()=>{try{await window.AXMInterglassExecutor.arm(I,frame)}catch(error){setInterglassState('CONTAINMENT_EVIDENCE_MISSING',error.message)}};run.onclick=()=>window.AXMInterglassExecutor.runOnce();release.onclick=()=>window.AXMInterglassExecutor.release();}
function selectMirror(index){activeMirror=Math.max(0,Math.min(index,(S.mirrors||[]).length-1));debug.activeMirrorIndex=activeMirror;const mirror=(S.mirrors||[])[activeMirror];const response=responseForMirror(activeMirror);$('response').textContent=response?.lines?.join('\n')||'Recorded mirror observation has no structural response packet.';renderWhy(whyForFormation(mirror?.formationSha256));$('mirrors').querySelectorAll('[data-m]').forEach((button,i)=>button.classList.toggle('active',i===activeMirror));inspect({mirror,structuralResponse:response,why:whyForFormation(mirror?.formationSha256),truth:'Mirror observes only; this response is inert structural text, not executable code.'})}
function render(){
 $('load').hidden=true;$('workspace').hidden=false;debug.loaded=true;
 $('facts').innerHTML=[['profiles',S.profileCount],['atoms',S.atomCount],['tick',S.cycle.tick],['seed',short(S.rootSeed)],['condition',short(S.cycle.conditionSha256)]].map(([a,b])=>`<span class="fact">${esc(a)}: ${esc(b)}</span>`).join('');
 const cv=S.cycle.interactionCoverage||{};$('coverage').textContent=`observed ${cv.observedProfileCountEver||0}/${cv.availableProfileCount||S.profileCount} · direct ${(S.cycle.influenceCarries||[]).filter(x=>x.crossGrammar).length}`;$('profileCount').textContent=`${S.profileCount} profiles`;
 const memory=S.contactMemory||{};$('memoryMetrics').innerHTML=[['edges',memory.contactEdgeCount||0],['multi-hop',memory.multiHopPathCount||0],['applied now',(S.appliedMemoryCarries||[]).length]].map(([a,b])=>`<div class="metric"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('');
 $('mirrors').innerHTML=(S.mirrors||[]).map((m,i)=>`<button class="card" data-m="${i}"><b>${esc(m.mirrorLens)}</b><small>${esc(m.compositeLineage?.kind||'formation')} · ${esc(short(m.formationSha256,18))}</small></button>`).join('')||'<div class="muted">No mirror observations captured.</div>';
 $('mirrors').querySelectorAll('[data-m]').forEach(button=>button.onclick=()=>selectMirror(+button.dataset.m));
 $('stars').innerHTML=(S.draftSky||[]).map((st,i)=>`<button class="star" data-s="${i}">${esc((st.languageIds||[]).join(' × '))} · tick ${esc(st.cycleStep)}</button>`).join('');$('stars').querySelectorAll('[data-s]').forEach(button=>button.onclick=()=>inspect(S.draftSky[+button.dataset.s]));
 const C=S.constellation||{};$('constellation').textContent=short(C.constellationDigest,24);$('ledger').innerHTML=[['events',C.eventCount],['stars',C.starCount],['failed',C.failedFormationCount],['contradictory',C.contradictoryFormationCount],['full saves',C.fullSaveReferenceCount],['authority','NONE']].map(([a,b])=>`<div class="tile"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('');
 const langs=[...new Map(S.cycle.atoms.map(a=>[a.languageId,a])).values()].sort((a,b)=>a.languageId.localeCompare(b.languageId));$('languages').innerHTML=langs.map((a,i)=>`<button class="lang" data-l="${i}">${esc(a.languageId)}</button>`).join('');$('languages').querySelectorAll('[data-l]').forEach(button=>button.onclick=()=>inspect(langs[+button.dataset.l]));
 drawSky();renderInterglass();if((S.mirrors||[]).length)selectMirror(0);else{renderWhy(null);inspect({claim:'Recorded snapshot only; moving interpolation creates no evidence.',sourceMode:S.sourceMode,profileSnapshotSha256:S.profileSnapshotSha256,rootSeed:S.rootSeed,contactMemory:S.contactMemory,interglass:S.interglass,truth:S.truth})}startMotion();
}
function loadSnapshot(x){if(!valid(x))throw Error('Not a Grammar Glass visual snapshot');S=x;render()}
$('file').addEventListener('change',async event=>{try{const file=event.target.files&&event.target.files[0];if(!file)return;const loader=window.AXMGrammarGlassSnapshotLoader;loadSnapshot(loader?await loader.parse(file):JSON.parse(await file.text()))}catch(error){alert(error.message)}});
$('motionToggle').addEventListener('click',()=>{const now=performance.now();if(motion){motion=false;pausedAt=now;$('motionToggle').textContent='PLAY';$('motionToggle').setAttribute('aria-pressed','false')}else{motion=true;pausedAccum+=now-pausedAt;pausedAt=0;$('motionToggle').textContent='PAUSE';$('motionToggle').setAttribute('aria-pressed','true')}});
$('speed').addEventListener('input',event=>{speed=Math.max(.2,Math.min(2.2,Number(event.target.value||100)/100))});
$('field').addEventListener('click',event=>{if(!S||!lastPoints.size)return;const rect=$('field').getBoundingClientRect(),scaleX=$('field').width/rect.width,scaleY=$('field').height/rect.height,x=(event.clientX-rect.left)*scaleX,y=(event.clientY-rect.top)*scaleY;let best=null,bestD=Infinity;for(const atom of S.cycle.atoms){const p=lastPoints.get(atom.atomId);if(!p)continue;const dist=Math.hypot(p.x-x,p.y-y);if(dist<bestD){bestD=dist;best=atom}}if(best&&bestD<28*(devicePixelRatio||1))inspect(best)});
addEventListener('resize',()=>{if(S){drawField(performance.now());drawSky()}});
if(window.GRAMMAR_GLASS_SNAPSHOT){try{loadSnapshot(window.GRAMMAR_GLASS_SNAPSHOT)}catch(error){console.error(error)}}
})();
