(()=>{'use strict';
const Intake=window.AXMGrammarGlass102IntakeCore,Ripple=window.AXMGrammarGlassChangeRippleCore,$=id=>document.getElementById(id);let glass=null,primary=null,ghost=null,receipt=null,depth=3,options=[],comparisonSha=null,raf=0;
const dbg=window.__GRAMMAR_GLASS_CHANGE_RIPPLE_STATE__={ready:false,changeCount:0,activeItemId:null,activeLensId:null,changeRippleSha256:null,structuralContactNotCausalProof:true,darkGrammarContactIsNotResolution:true,visualizationCreatesEvidence:false,authority:'NONE'};
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function point(a,w,h){const angle=Number(a?.position?.angle||0),radius=Math.max(.08,Math.min(1,Number(a?.position?.radius||.55))),scale=Math.min(w,h)*.39;return{x:w/2+Math.cos(angle)*radius*scale,y:h/2+Math.sin(angle)*radius*scale}}
function install(){const wrap=$('fieldWrap');if(wrap&&!$('changeRippleCanvas')){const c=document.createElement('canvas');c.id='changeRippleCanvas';c.className='change-ripple-canvas';c.setAttribute('aria-label','102-Grammar structural change ripple projection');wrap.appendChild(c)}const card=$('grammar102Status')?.closest('.grammar102-card');if(card&&!$('changeRippleItem')){const box=document.createElement('div');box.className='change-ripple-box';box.innerHTML=`<div class="change-ripple-head"><b>CHANGE RIPPLE · IMPACT LENS</b><span id="changeRippleStatus">WAIT A/B</span></div><div class="change-ripple-controls"><input id="changeRippleSearch" placeholder="filter changed item"><select id="changeRippleItem"><option value="">No changed items</option></select><select id="changeRippleDepth"><option value="1">1 · ORIGIN</option><option value="2">2 · LANGUAGE</option><option value="3" selected>3 · NEIGHBORHOOD</option><option value="4">4 · CONSTELLATION</option></select><button id="changeRippleTrace">TRACE RIPPLE</button><button id="changeRippleClear">CLEAR RIPPLE</button><button id="changeRippleInspect">INSPECT</button></div><div class="change-ripple-readout" id="changeRippleReadout">Changed 102 item → recorded Glass contact. Structural trace only, never causal proof.</div>`;card.appendChild(box)}if(!$('changeRippleStyles')){const s=document.createElement('style');s.id='changeRippleStyles';s.textContent=`.change-ripple-canvas{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;mix-blend-mode:screen;z-index:12}.change-ripple-box{margin-top:.6rem;padding:.6rem;border:1px solid rgba(255,213,106,.2);border-radius:11px;background:rgba(255,213,106,.025)}.change-ripple-head{display:flex;align-items:center;justify-content:space-between;gap:.5rem;margin-bottom:.45rem}.change-ripple-head b{font:800 10px/1 ui-monospace,monospace;letter-spacing:.07em}.change-ripple-head span{font:700 9px/1 ui-monospace,monospace;opacity:.68}.change-ripple-controls{display:grid;grid-template-columns:1fr 1.3fr .75fr;gap:.35rem}.change-ripple-controls input,.change-ripple-controls select,.change-ripple-controls button{min-width:0;border:1px solid rgba(255,213,106,.2);background:rgba(8,17,29,.9);color:inherit;border-radius:8px;padding:.45rem;font:700 9px/1.1 ui-monospace,monospace}.change-ripple-controls button{cursor:pointer}.change-ripple-readout{margin-top:.45rem;padding:.45rem;border-left:2px solid rgba(255,213,106,.55);font:600 9px/1.4 ui-monospace,monospace;opacity:.75}@media(max-width:780px){.change-ripple-controls{grid-template-columns:1fr 1fr}.change-ripple-controls input,.change-ripple-controls select{grid-column:1/-1}}`;document.head.appendChild(s)}}
function setInspector(v){const e=$('inspector');if(e)e.textContent=typeof v==='string'?v:JSON.stringify(v,null,2)}
function selectedLensIds(){return window.AXMGrammarGlass102View?.getState?.().selectedLensIds||[]}
function buildOptions(){
 options=[];comparisonSha=null;if(primary&&ghost){const cmp=Intake.compareGenerations(primary,ghost);comparisonSha=cmp.generationComparisonSha256;const chosen=new Set(selectedLensIds()),layers=chosen.size?cmp.layers.filter(l=>chosen.has(l.lensId)):cmp.layers;for(const l of layers){for(const [status,key] of [['CHANGED','changed'],['ADDED','added'],['REMOVED','removed']])for(const itemId of l.itemDelta?.[key]||[])options.push({lensId:l.lensId,itemId,status})}}
 const order={CHANGED:0,ADDED:1,REMOVED:2};options.sort((a,b)=>order[a.status]-order[b.status]||a.lensId.localeCompare(b.lensId)||a.itemId.localeCompare(b.itemId));dbg.changeCount=options.length;renderOptions();
}
function renderOptions(){const sel=$('changeRippleItem');if(!sel)return;const q=String($('changeRippleSearch')?.value||'').trim().toLowerCase(),filtered=q?options.filter(x=>`${x.lensId} ${x.itemId} ${x.status}`.toLowerCase().includes(q)):options;sel.innerHTML='';for(const x of filtered.slice(0,300)){const o=document.createElement('option');o.value=JSON.stringify([x.lensId,x.itemId]);o.textContent=`${x.status} · ${x.lensId} · ${x.itemId}`;sel.appendChild(o)}if(!sel.options.length){const o=document.createElement('option');o.value='';o.textContent=options.length?'No filter matches':'No changed items';sel.appendChild(o)}status()}
function drawLine(ctx,a,b,color,alpha,d,dashed=false){if(!a||!b)return;ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.lineWidth=Math.max(1,d);if(dashed)ctx.setLineDash([4*d,5*d]);ctx.stroke();ctx.restore()}
function draw(){
 const c=$('changeRippleCanvas');if(!c)return;const[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(!receipt||receipt.result!=='GRAMMAR_102_CHANGE_RIPPLE_READY_STRUCTURAL_CONTACT_ONLY'||!glass){raf=0;return}
 const atoms=new Map((glass.cycle?.atoms||[]).map(a=>[a.atomId,a])),originIds=new Set(receipt.stages.language.atomRefs.map(a=>a.atomId)),pulse=1+Math.sin(performance.now()/180)*.11;
 if(depth>=2){for(const id of originIds){const a=atoms.get(id),p=a?point(a,w,h):null;if(!p)continue;ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,10*d*pulse,0,Math.PI*2);ctx.strokeStyle='#ffd56a';ctx.globalAlpha=.82;ctx.lineWidth=Math.max(1.2,d);ctx.shadowColor='#ffd56a';ctx.shadowBlur=16*d;ctx.stroke();ctx.restore()}}
 if(depth>=3){for(const e of receipt.stages.neighborhood.relationRefs){const a=atoms.get(e.leftAtomId),b=atoms.get(e.rightAtomId),dark=receipt.stages.neighborhood.darkGrammarRelationRefs.some(x=>x.leftAtomId===e.leftAtomId&&x.rightAtomId===e.rightAtomId&&x.connectionClass===e.connectionClass);drawLine(ctx,a&&point(a,w,h),b&&point(b,w,h),dark?'#b89aff':'#5ee7ff',dark?0.8:0.34,d,false)}for(const e of receipt.stages.neighborhood.directCarryRefs){const a=atoms.get(e.sourceAtomId),b=atoms.get(e.targetAtomId);drawLine(ctx,a&&point(a,w,h),b&&point(b,w,h),'#7df6be',.5,d,true)}for(const m of receipt.stages.neighborhood.contactMemoryRefs){const ps=(m.pathAtomIds||[]).map(id=>atoms.get(id)).filter(Boolean).map(a=>point(a,w,h));for(let i=1;i<ps.length;i++)drawLine(ctx,ps[i-1],ps[i],'#ffba7a',.24,d,true)}for(const a of receipt.stages.neighborhood.neighborAtomRefs){const p=point(a,w,h);ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,3*d,0,Math.PI*2);ctx.fillStyle='#edf5ff';ctx.globalAlpha=.34;ctx.fill();ctx.restore()}}
 if(depth>=4){for(const s of [...receipt.stages.constellation.draftStarRefs,...receipt.stages.constellation.runStarRefs]){if(!s.x&&!s.y)continue;const p={x:w/2+Number(s.x)*w*.43,y:h/2+Number(s.y)*h*.42};ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,6*d,0,Math.PI*2);ctx.strokeStyle=s.runStarSha256?'#ffc86b':'#b89aff';ctx.globalAlpha=.72;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=10*d;ctx.stroke();ctx.restore()}}
 ctx.save();ctx.font=`${10*d}px ui-monospace,monospace`;ctx.fillStyle='#ffd56a';ctx.globalAlpha=.85;ctx.fillText(`${receipt.origin.changeClass} · ${receipt.origin.itemId}`,10*d,18*d);ctx.fillStyle='#edf5ff';ctx.globalAlpha=.62;ctx.fillText(`→ ${receipt.origin.languageId} · structural contact only`,10*d,32*d);if(receipt.metrics.darkGrammarRelationContactCount)ctx.fillText(`DARK GRAMMAR CONTACT ${receipt.metrics.darkGrammarRelationContactCount} · NOT RESOLUTION`,10*d,46*d);ctx.restore();
 raf=requestAnimationFrame(draw);
}
function startDraw(){cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
function clearRipple(){receipt=null;cancelAnimationFrame(raf);raf=0;dbg.ready=false;dbg.activeItemId=null;dbg.activeLensId=null;dbg.changeRippleSha256=null;const c=$('changeRippleCanvas');if(c){const ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height)}status()}
function trace(){const raw=$('changeRippleItem')?.value;if(!raw||!glass||!primary||!ghost)return;let pair;try{pair=JSON.parse(raw)}catch{return}try{receipt=Ripple.createChangeRipple(glass,primary,ghost,{lensId:pair[0],itemId:pair[1]});dbg.ready=receipt.result==='GRAMMAR_102_CHANGE_RIPPLE_READY_STRUCTURAL_CONTACT_ONLY';dbg.activeLensId=pair[0];dbg.activeItemId=pair[1];dbg.changeRippleSha256=receipt.changeRippleSha256;status();if(dbg.ready)startDraw();else setInspector(receipt)}catch(error){setInspector(error.message)}}
function inspect(){if(receipt)setInspector({changeRipple:receipt,truth:'Changed imported capability → recorded Glass structural neighborhood. Contact is not causation, improvement, regression, semantic equivalence, or Dark-Grammar resolution.'})}
function status(){const e=$('changeRippleStatus');if(e)e.textContent=!primary||!ghost?'WAIT A/B':receipt?(dbg.ready?'RIPPLE READY':'HELD'):`${options.length} CHANGES`;const r=$('changeRippleReadout');if(r){r.textContent=receipt&&dbg.ready?`${receipt.origin.languageId} · ${receipt.metrics.originAtomCount} atoms · ${receipt.metrics.relationCount} relations · ${receipt.metrics.directCarryCount} carries · ${receipt.metrics.contactMemoryPathCount} memory paths · ${receipt.metrics.draftStarCount}/${receipt.metrics.runStarCount} Draft/Run stars · dark contact ${receipt.metrics.darkGrammarRelationContactCount} (not resolution)`:`${options.length} changed/added/removed items available. Structural trace only, never causal proof.`}}
async function load(file,slot){if(!file)return;const loader=window.AXMGrammarGlassSnapshotLoader,raw=loader?await loader.parse(file):JSON.parse(await file.text()),r=Intake.createImportReceipt(raw);if(slot==='primary')primary=r;else ghost=r;clearRipple();buildOptions()}
function bindGlass(s){if(s?.schema==='axm.code.grammar-glass-visual-snapshot.v1'){glass=s;clearRipple()}}
function setup(){if(!Intake||!Ripple)return;install();$('grammar102PrimaryFile')?.addEventListener('change',async e=>{try{await load(e.target.files&&e.target.files[0],'primary')}catch(error){setInspector(error.message)}});$('grammar102GhostFile')?.addEventListener('change',async e=>{try{await load(e.target.files&&e.target.files[0],'ghost')}catch(error){setInspector(error.message)}});addEventListener('axm:grammar-glass-snapshot-loaded',e=>bindGlass(e.detail?.snapshot));$('changeRippleSearch')?.addEventListener('input',renderOptions);$('changeRippleDepth')?.addEventListener('change',e=>{depth=Math.max(1,Math.min(4,Number(e.target.value||3)));if(receipt)startDraw()});$('changeRippleTrace')?.addEventListener('click',trace);$('changeRippleClear')?.addEventListener('click',clearRipple);$('changeRippleInspect')?.addEventListener('click',inspect);addEventListener('axm:grammar-glass-102-view-changed',e=>{const old=comparisonSha;if(e.detail?.primaryLoaded===false)primary=null;if(e.detail?.ghostLoaded===false)ghost=null;buildOptions();if(e.detail?.primaryLoaded===false||e.detail?.ghostLoaded===false||(old&&comparisonSha&&old!==comparisonSha))clearRipple()});if(window.GRAMMAR_GLASS_SNAPSHOT)bindGlass(window.GRAMMAR_GLASS_SNAPSHOT);status()}
window.AXMGrammarGlassChangeRipple=Object.freeze({bindGlass,clearRipple,getReceipt:()=>receipt,getState:()=>({...dbg,depth,comparisonSha256:comparisonSha}),contract:Object.freeze({structuralContactNotCausalProof:true,darkGrammarContactIsNotResolution:true,visualizationCreatesEvidence:false,authority:'NONE'})});setup();
})();
