(()=>{'use strict';
const Ext=window.AXMGrammarGlassPlaygroundExtensionsCore,$=id=>document.getElementById(id);let S=null,plan=null,index=0,playing=false,timer=null,trail=[];
const dbg=window.__GRAMMAR_GLASS_REPLAY_STATE__={loaded:false,playing:false,eventIndex:0,eventCount:0,replayCreatesEvidence:false,replayFeedsTwisterAutomatically:false,orchestraEventDispatch:true,authority:'NONE'};
const frameLayer=window.AXMGrammarGlassFrameSteward.registerLayer('constellation-replay',{mode:'ON_DEMAND',draw});
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function short(v,n=12){v=String(v||'');return v.length>n?v.slice(0,n)+'…':v||'—'}
function eventPoint(e,w,h){let x=Number(e?.x||0),y=Number(e?.y||0);if(Math.abs(x)>.0001||Math.abs(y)>.0001)return{x:w/2+x*w*.43,y:h/2+y*h*.42};const raw=String(e?.digest||`${e?.kind}:${e?.index}`),a=parseInt(raw.slice(0,8).replace(/[^0-9a-f]/gi,'')||'1',16)/0xffffffff*Math.PI*2,r=.22+(parseInt(raw.slice(8,16).replace(/[^0-9a-f]/gi,'')||'2',16)/0xffffffff)*.26;return{x:w/2+Math.cos(a)*r*w,y:h/2+Math.sin(a)*r*h}}
function setStatus(){const e=plan?.events?.[index]||null,el=$('replayStatus');if(el)el.textContent=e?`${index+1}/${plan.events.length} · ${e.kind.replace('_',' ')}`:'EMPTY';const slider=$('replayScrub');if(slider&&plan){slider.max=Math.max(0,plan.events.length-1);slider.value=index}const label=$('replayLabel');if(label)label.textContent=e?`${(e.languageIds||[]).join(' × ')||'recorded star'} · ${short(e.digest,18)}${e.resultClass?` · ${e.resultClass}`:''}`:'No recorded star events.';dbg.eventIndex=index;dbg.eventCount=plan?.events?.length||0}
function focus(i){if(!plan?.events?.length)return;index=Math.max(0,Math.min(plan.events.length-1,Number(i)||0));const e=plan.events[index];trail.push(e);if(trail.length>8)trail.shift();setStatus();frameLayer.invalidate();if(window.AXMGrammarGlassVesselView&&window.AXMGrammarGlassVesselView.focusLineage)window.AXMGrammarGlassVesselView.focusLineage({kind:e.kind==='RUN_STAR'?'RUN':'DRAFT',digest:e.digest,resultClass:e.resultClass,languageIds:e.languageIds});dispatchEvent(new CustomEvent('axm:grammar-glass-replay-focus',{detail:{event:e,index,replayPlanSha256:plan.replayPlanSha256}}));if($('inspector'))$('inspector').textContent=JSON.stringify({replayEvent:e,replayPlanSha256:plan.replayPlanSha256,truth:'Recorded star-flight replay only. Replay creates no events, evidence, ranking or Twister re-entry.'},null,2)}
function speed(){return Math.max(.25,Math.min(3,Number($('replaySpeed')?.value||100)/100))}
function step(){if(!playing||!plan?.events?.length)return;focus((index+1)%plan.events.length);timer=setTimeout(step,900/speed())}
function toggle(){playing=!playing;dbg.playing=playing;const b=$('replayToggle');if(b){b.classList.toggle('active',playing);b.textContent=playing?'PAUSE FLIGHT':'STAR FLIGHT'}clearTimeout(timer);dispatchEvent(new CustomEvent('axm:grammar-glass-replay-state',{detail:{playing}}));if(playing){frameLayer.invalidate();step()}else frameLayer.sleep()}
function draw(){const c=$('replayCanvas');if(!c)return;const[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(plan?.events?.length){const points=trail.map(e=>({e,p:eventPoint(e,w,h)}));for(let i=1;i<points.length;i++){ctx.save();ctx.beginPath();ctx.moveTo(points[i-1].p.x,points[i-1].p.y);ctx.lineTo(points[i].p.x,points[i].p.y);ctx.strokeStyle='#d7ff8a';ctx.globalAlpha=.12+i/points.length*.25;ctx.lineWidth=Math.max(1,d);ctx.stroke();ctx.restore()}const e=plan.events[index],p=eventPoint(e,w,h),pulse=1+Math.sin(performance.now()/160)*.13;for(let r=0;r<3;r++){ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,(8+r*8)*d*pulse,0,Math.PI*2);ctx.strokeStyle=e.kind==='RUN_STAR'?'#ffc86b':'#b89aff';ctx.globalAlpha=.5-r*.12;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=14*d;ctx.stroke();ctx.restore()}ctx.save();ctx.font=`${10*d}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.82;ctx.fillText(e.kind==='RUN_STAR'?'RUN STAR':'DRAFT STAR',p.x+12*d,p.y-8*d);ctx.restore()}if(playing)frameLayer.invalidate()}
function bind(snapshot){if(!snapshot||snapshot.schema!=='axm.code.grammar-glass-visual-snapshot.v1')return;S=snapshot;plan=Ext.createReplayPlan(S);index=0;trail=[];dbg.loaded=true;playing=false;dbg.playing=false;clearTimeout(timer);setStatus();attachStarClicks();frameLayer.invalidate()}
function attachStarClicks(){const root=$('stars');if(!root)return;root.querySelectorAll('[data-s]').forEach(btn=>{if(btn.dataset.replayBound)return;btn.dataset.replayBound='1';btn.addEventListener('click',()=>{const draftIndex=Number(btn.dataset.s||0),target=plan?.events?.findIndex(e=>e.kind==='DRAFT_STAR'&&e.index===draftIndex);if(target>=0)focus(target)})})}
function setup(){const toggleBtn=$('replayToggle'),prev=$('replayPrev'),next=$('replayNext'),scrub=$('replayScrub'),inspect=$('replayInspect');if(toggleBtn)toggleBtn.onclick=toggle;if(prev)prev.onclick=()=>focus(index-1);if(next)next.onclick=()=>focus(index+1);if(scrub)scrub.oninput=()=>focus(Number(scrub.value||0));if(inspect)inspect.onclick=()=>plan&&$('inspector')&&($('inspector').textContent=JSON.stringify(plan,null,2));const stars=$('stars');if(stars)new MutationObserver(attachStarClicks).observe(stars,{childList:true,subtree:true});addEventListener('axm:grammar-glass-snapshot-loaded',e=>bind(e.detail?.snapshot));if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT)}
window.AXMGrammarGlassConstellationReplay=Object.freeze({bind,focus,toggle,getPlan:()=>plan,getState:()=>({...dbg}),contract:Object.freeze({replayCreatesEvidence:false,replayCreatesEvents:false,replayFeedsTwisterAutomatically:false,orchestraEventDispatch:true,ranking:false,authority:'NONE'})});setup();
})();
