(()=>{'use strict';
const Core=window.AXMGrammarGlassDiscoveryKilnCore,$=id=>document.getElementById(id);let S=null,probe=null,ledger=null,preparation=null,storageAvailable=true,unsub=null;
const dbg=window.__GRAMMAR_GLASS_DISCOVERY_KILN_STATE__={loaded:false,combinationIdentitySha256:null,localStatus:'EMPTY',preparationState:'EMPTY',holdReason:null,ledgerEventCount:0,storage:'LOCAL_ONLY',executionAuthority:false,automaticPromotion:false};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=(v,n=12)=>v?String(v).slice(0,n)+'…':'—';
function storageKey(){return S?`axm.grammar-glass.discovery-ledger.v1:${Core.sourceKey(S)}`:null}
function loadLedger(){ledger=Core.emptyLedger(S);storageAvailable=true;try{const raw=localStorage.getItem(storageKey());if(raw){const parsed=JSON.parse(raw);if(Core.validLedger(parsed)&&parsed.sourceKey===Core.sourceKey(S))ledger=parsed}}catch{storageAvailable=false}dbg.storage=storageAvailable?'LOCAL_DEVICE':'SESSION_ONLY'}
function saveLedger(){if(!storageAvailable)return;try{localStorage.setItem(storageKey(),JSON.stringify(ledger))}catch{storageAvailable=false;dbg.storage='SESSION_ONLY'}}
function rail(){const root=$('kilnRail');if(!root)return;const states=preparation?.stateRail||[{state:'ROLLED',evidenceDigest:probe?.exploration?.combinationIdentitySha256||null}];const reached=new Map(states.map(item=>[item.state,item]));root.innerHTML=Core.STATES.map(state=>{const item=reached.get(state),active=!!item;return`<div class="kiln-stage${active?' reached':''}${state==='HELD'&&active?' held':''}"><i></i><b>${esc(state.replaceAll('_',' '))}</b><small>${item?esc(short(item.evidenceDigest,9)):'—'}</small></div>`}).join('')}
function render(){const status=$('kilnStatus'),identity=$('kilnIdentity'),history=$('kilnHistory'),grounding=$('kilnGrounding'),prepare=$('kilnPrepare'),arm=$('kilnArm'),run=$('kilnRun'),exp=$('kilnExport');const combination=probe?.exploration?.combinationIdentitySha256||null,summary=combination&&ledger?Core.combinationSummary(ledger,combination):null;dbg.loaded=!!S;dbg.combinationIdentitySha256=combination;dbg.localStatus=summary?.localStatus||'EMPTY';dbg.preparationState=preparation?.result||'EMPTY';dbg.holdReason=preparation?.holdReason||null;dbg.ledgerEventCount=ledger?.eventCount||0;if(status)status.textContent=preparation?.result==='DISCOVERY_PREPARATION_BOUND_TO_EXISTING_CANDIDATE'?'CANDIDATE BOUND':preparation?'HELD · ADAPTER':probe?'READY TO PREPARE':'WAITING FOR ROLL';if(identity)identity.textContent=combination?short(combination,20):'no active combination';if(history)history.innerHTML=summary?`<span>LOCAL HISTORY</span><b>${esc(summary.localStatus.replaceAll('_',' '))}</b><small>${summary.preparationCount} prepared · ${summary.testCount} tested · ${esc(dbg.storage.replaceAll('_',' '))}</small>`:'<span>LOCAL HISTORY</span><b>EMPTY</b><small>Choose or roll real grammars first.</small>';if(grounding){const g=preparation?.grounding;grounding.innerHTML=g?`<span>GROUNDING</span><b>${g.selectedAtomCount} atoms · ${g.relationCount} relations · ${g.directCarryCount} carries</b><small>${preparation.holdReason?esc(preparation.holdReason.replaceAll('_',' ')):'existing recorded candidate lineage found'}</small>`:probe?`<span>GROUNDING AVAILABLE</span><b>${probe.metrics.selectedAtomCount} atoms · ${probe.metrics.relationEdgeCount} relations</b><small>Preparation records exact refs; it does not claim novelty.</small>`:'<span>GROUNDING</span><b>WAITING</b><small>No candidate has been constructed.</small>'}if(prepare)prepare.disabled=!probe;if(arm)arm.disabled=preparation?.result!=='DISCOVERY_PREPARATION_BOUND_TO_EXISTING_CANDIDATE';if(run)run.disabled=arm?.disabled!==false||$('runCandidate')?.disabled!==false;if(exp)exp.disabled=!ledger?.eventCount;rail()}
function prepare(){if(!S||!probe)return;try{preparation=Core.createPreparation({snapshot:S,probe,ledger});ledger=Core.recordPreparation(ledger,preparation);saveLedger();render();$('inspector').textContent=JSON.stringify({discoveryPreparation:preparation,localLedgerSummary:Core.combinationSummary(ledger,preparation.combinationIdentitySha256),truth:'This local preparation either binds exact existing lineage or stops at a visible adapter hold. It does not generate arbitrary source code, prove novelty, execute, or promote anything.'},null,2)}catch(error){dbg.preparationState='HELD';dbg.holdReason=error.message;$('inspector').textContent=error.message;render()}}
function inspect(){const summary=probe&&ledger?Core.combinationSummary(ledger,probe.exploration.combinationIdentitySha256):null;$('inspector').textContent=JSON.stringify({discoveryPreparation:preparation,localCombinationSummary:summary,ledgerBinding:ledger?{sourceKey:ledger.sourceKey,eventCount:ledger.eventCount,ledgerSha256:ledger.ledgerSha256,storage:dbg.storage}:null},null,2)}
function exportLedger(){if(!ledger?.eventCount)return;const blob=new Blob([JSON.stringify(ledger,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`grammar-glass-local-discovery-ledger-${ledger.sourceKey.slice(0,12)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function onRuntime(event){if(!preparation||!ledger)return;if(!['PASS_OBSERVED','FAIL_OBSERVED','CRASH_OBSERVED','TIMEOUT_OBSERVED'].includes(event.state)||!event.detail?.receipt){render();return}try{ledger=Core.recordSandboxReceipt(ledger,{preparation,receipt:event.detail.receipt});saveLedger();render()}catch(error){dbg.holdReason=error.message;render()}}
function bind(snapshot){if(!window.AXMGrammarGlassPlaygroundCore.validSnapshot(snapshot))return;S=snapshot;probe=null;preparation=null;loadLedger();render()}
function setup(){const prepareButton=$('kilnPrepare'),inspectButton=$('kilnInspect'),exportButton=$('kilnExport'),armButton=$('kilnArm'),runButton=$('kilnRun');if(prepareButton)prepareButton.onclick=prepare;if(inspectButton)inspectButton.onclick=inspect;if(exportButton)exportButton.onclick=exportLedger;if(armButton)armButton.onclick=()=>$('armCandidate')?.click();if(runButton)runButton.onclick=()=>$('runCandidate')?.click();addEventListener('axm:grammar-glass-probe-changed',event=>{probe=event.detail?.probe||null;preparation=null;render()});addEventListener('axm:grammar-glass-snapshot-loaded',event=>bind(event.detail?.snapshot));if(window.AXMInterglassExecutor)unsub=window.AXMInterglassExecutor.on(onRuntime);if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);render()}
window.AXMGrammarGlassDiscoveryKiln=Object.freeze({getPreparation:()=>preparation,getLedger:()=>ledger,getState:()=>({...dbg}),destroy:()=>unsub?.(),contract:Object.freeze({localLedgerOnly:true,newFormationRequiresFullRecordedCycle:true,arbitrarySourceGeneration:false,executionAuthority:false,automaticPromotion:false})});setup();
})();
