(()=>{'use strict';
const Core=window.AXMGrammarGlassGhostCore,$=id=>document.getElementById(id);let primary=null,ghost=null,comparison=null,blend=.5;
const dbg=window.__GRAMMAR_GLASS_GHOST_STATE__={primaryLoaded:false,ghostLoaded:false,comparisonSha256:null,ghostOverlayCreatesEvidence:false,comparisonRanksSnapshots:false,cosmologyClaimMade:false,authority:'NONE'};
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function point(a,w,h){const angle=Number(a.position?.angle||0),radius=Math.max(.08,Math.min(1,Number(a.position?.radius||.55))),scale=Math.min(w,h)*.39;return{x:w/2+Math.cos(angle)*radius*scale,y:h/2+Math.sin(angle)*radius*scale}}
function draw(){const c=$('ghostGlassCanvas');if(!c)return;const[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(!primary||!ghost)return;const P=new Map((primary.cycle.atoms||[]).map(a=>[a.atomId,a])),G=new Map((ghost.cycle.atoms||[]).map(a=>[a.atomId,a])),ids=[...new Set([...P.keys(),...G.keys()])].sort();const membrane=blend*w;ctx.save();ctx.beginPath();ctx.moveTo(membrane,h*.08);ctx.lineTo(membrane,h*.9);ctx.strokeStyle='#edf5ff';ctx.globalAlpha=.28;ctx.lineWidth=Math.max(1,d);ctx.shadowColor='#b89aff';ctx.shadowBlur=22*d;ctx.stroke();ctx.restore();let trails=0;for(let i=0;i<ids.length;i++){const id=ids[i],a=P.get(id),b=G.get(id),pa=a?point(a,w,h):null,pb=b?point(b,w,h):null;if(pa&&pb&&i%11===0&&trails<90){ctx.save();ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.strokeStyle='#8fa4bc';ctx.globalAlpha=.06+.11*Math.abs(.5-blend)*2;ctx.stroke();ctx.restore();trails++}if(pa&&i%3===0){ctx.save();ctx.beginPath();ctx.arc(pa.x,pa.y,1.2*d,0,Math.PI*2);ctx.fillStyle='#5ee7ff';ctx.globalAlpha=.28*(1-blend);ctx.fill();ctx.restore()}if(pb&&i%3===0){ctx.save();ctx.beginPath();ctx.arc(pb.x,pb.y,1.4*d,0,Math.PI*2);ctx.fillStyle='#b89aff';ctx.shadowColor='#b89aff';ctx.shadowBlur=5*d;ctx.globalAlpha=.16+.42*blend;ctx.fill();ctx.restore()}}ctx.save();ctx.font=`${10*d}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.58;ctx.fillText('PRIMARY',12*d,20*d);ctx.fillText('GHOST',Math.max(12*d,w-56*d),20*d);ctx.fillText('MEMBRANE',Math.max(6*d,membrane-30*d),h*.92);ctx.restore()}
function status(){const e=$('ghostStatus');if(e)e.textContent=comparison?`BOUND · ${comparison.metrics.sharedGrammarCount} SHARED`:(ghost?'WAIT PRIMARY':'EMPTY');const b=$('ghostBlendValue');if(b)b.textContent=`${Math.round(blend*100)}%`;dbg.primaryLoaded=!!primary;dbg.ghostLoaded=!!ghost;dbg.comparisonSha256=comparison?.ghostComparisonSha256||null}
function rebuild(){comparison=null;if(primary&&ghost){try{comparison=Core.createGhostComparison(primary,ghost)}catch(error){if($('inspector'))$('inspector').textContent=error.message}}status();draw();dispatchEvent(new CustomEvent('axm:grammar-glass-ghost-changed',{detail:{comparison,ghostLoaded:!!ghost}}))}
function bindPrimary(s){if(!s||s.schema!=='axm.code.grammar-glass-visual-snapshot.v1')return;primary=s;rebuild()}
async function loadGhost(file){if(!file)return;const s=JSON.parse(await file.text());if(!s||s.schema!=='axm.code.grammar-glass-visual-snapshot.v1')throw Error('GHOST_GLASS_VALID_SNAPSHOT_REQUIRED');ghost=s;rebuild()}
function inspect(){if(!comparison)return;if($('inspector'))$('inspector').textContent=JSON.stringify({ghostComparison:comparison,truth:'Parallel recorded-snapshot comparison only. No winner, ranking, causal proof, or cosmology claim.'},null,2)}
function clearGhost(){ghost=null;comparison=null;const f=$('ghostFile');if(f)f.value='';rebuild()}
function loadGrammar102Evolution(){if(window.AXMGrammarGlass102View)return;const scripts=['grammar-102-intake-core.js','grammar-102-visual-core.js','grammar-102-view.js'];let i=0;const next=()=>{if(i>=scripts.length)return;const src=scripts[i++];const s=document.createElement('script');s.src=src;s.async=false;s.onload=next;s.onerror=()=>{const e=$('inspector');if(e)e.textContent=`GRAMMAR_102_EVOLUTION_SCRIPT_LOAD_FAILED:${src}`};document.body.appendChild(s)};next()}
function setup(){const f=$('file'),g=$('ghostFile'),slider=$('ghostBlend'),inspectBtn=$('ghostInspect'),clear=$('ghostClear');if(f)f.addEventListener('change',async e=>{try{const file=e.target.files&&e.target.files[0];if(file)bindPrimary(JSON.parse(await file.text()))}catch{}});if(g)g.addEventListener('change',async e=>{try{await loadGhost(e.target.files&&e.target.files[0])}catch(error){if($('inspector'))$('inspector').textContent=error.message}});if(slider)slider.oninput=()=>{blend=Math.max(0,Math.min(1,Number(slider.value||50)/100));status();draw()};if(inspectBtn)inspectBtn.onclick=inspect;if(clear)clear.onclick=clearGhost;addEventListener('resize',draw);if(window.GRAMMAR_GLASS_SNAPSHOT)bindPrimary(window.GRAMMAR_GLASS_SNAPSHOT);status()}
window.AXMGrammarGlassGhost=Object.freeze({bindPrimary,clearGhost,getComparison:()=>comparison,getState:()=>({...dbg,blend}),contract:Object.freeze({ghostOverlayCreatesEvidence:false,comparisonRanksSnapshots:false,cosmologyClaimMade:false,grammar102EvolutionLoadsAsOptionalViewer:true,authority:'NONE'})});setup();loadGrammar102Evolution();
})();
