(()=>{'use strict';
const Ext=window.AXMGrammarGlassPlaygroundExtensionsCore,$=id=>document.getElementById(id);let S=null,ctx=null,master=null,panner=null,timer=null,playing=false,motionPaused=false,lastPlan=null;
const dbg=window.__GRAMMAR_GLASS_AUDIO_STATE__={loaded:false,playing:false,motionPaused:false,planSha256:null,eventCount:0,audioCreatesEvidence:false,audioIsCorrectnessSignal:false,stereoTouchCoupling:false,replayChimeCoupling:false,motionPauseCoupling:false,authority:'NONE'};
function currentProbe(){return window.AXMGrammarGlassPlayground&&window.AXMGrammarGlassPlayground.getProbe?window.AXMGrammarGlassPlayground.getProbe():null}
function currentMode(){return window.AXMGrammarGlassPlayground?.getState?.().mode||'GRAVITY_WELL'}
function touchReceipt(){return window.AXMGrammarGlassTouchLens?.getReceipt?.()||null}
function setStatus(v){const e=$('audioStatus');if(e)e.textContent=v}
function volume(){return Math.max(0,Math.min(.3,Number($('audioVolume')?.value||12)/100))}
function modeMultiplier(){return({GRAVITY_WELL:.78,RIFT_SCAN:1.22,DARK_MATTER:.62,STAR_HUNT:1.48})[currentMode()]||1}
function touchPan(){const r=touchReceipt();return r?Math.max(-1,Math.min(1,(Number(r.focus?.xNorm??.5)-.5)*2)):0}
function syncPan(){if(panner){panner.pan.setTargetAtTime(touchPan(),ctx?.currentTime||0,.03);dbg.stereoTouchCoupling=true}}
function oscillatorType(event){const r=touchReceipt();if(event.kind==='DIRECT_CARRY_PULSE')return r?.focus?.forceMode==='PUSH'?'sawtooth':'square';if(event.kind==='CONTACT_MEMORY_ECHO')return 'triangle';return currentMode()==='DARK_MATTER'?'triangle':'sine'}
function tone(event,at,extra={}){if(!ctx||!master||motionPaused)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),now=at+(extra.offsetMs??event.offsetMs??0)/1000,dur=Math.max(.04,(extra.durationMs??event.durationMs??100)/1000),g=Math.min(.08,Number(extra.gain??event.gain??.015));osc.frequency.setValueAtTime(Number(extra.frequency??event.frequency??220)*modeMultiplier(),now);osc.type=extra.type||oscillatorType(event);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,g),now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+dur);osc.connect(gain);gain.connect(master);osc.start(now);osc.stop(now+dur+.03)}
function buildPlan(){const probe=currentProbe();if(!S||!probe)return null;try{return Ext.createSonificationPlan(S,probe,{density:.62})}catch{return null}}
function cycle(){clearTimeout(timer);timer=null;if(!playing||!ctx||motionPaused)return;const plan=buildPlan();if(!plan){setStatus('SELECT GRAMMARS');timer=setTimeout(cycle,500);return}lastPlan=plan;dbg.planSha256=plan.sonificationPlanSha256;dbg.eventCount=plan.events.length;syncPan();const at=ctx.currentTime+.05;plan.events.forEach(e=>tone(e,at));setStatus(`ORCHESTRA · ${plan.events.length}`);const span=Math.max(1200,...plan.events.map(e=>e.offsetMs+e.durationMs))+420;timer=setTimeout(cycle,span)}
function replayChime(event){if(!playing||!ctx||!event||motionPaused)return;const raw=String(event.digest||event.kind||'star').replace(/[^0-9a-f]/gi,''),v=parseInt(raw.slice(0,6)||'abc123',16),frequency=(event.kind==='RUN_STAR'?523.25:392)*(1+(v%5)*.125);tone({kind:'REPLAY_STAR_CHIME',offsetMs:0,durationMs:180,gain:.028,frequency},ctx.currentTime+.02,{type:event.kind==='RUN_STAR'?'triangle':'sine'});dbg.replayChimeCoupling=true}
async function start(){if(playing)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC){setStatus('NO WEB AUDIO');return}ctx=new AC();await ctx.resume();master=ctx.createGain();master.gain.value=volume();panner=ctx.createStereoPanner?ctx.createStereoPanner():null;if(panner){master.connect(panner);panner.connect(ctx.destination)}else master.connect(ctx.destination);playing=true;motionPaused=false;dbg.playing=true;dbg.motionPaused=false;const b=$('audioToggle');if(b){b.classList.add('active');b.textContent='STOP SOUND'}syncPan();cycle()}
function stop(){playing=false;motionPaused=false;dbg.playing=false;dbg.motionPaused=false;clearTimeout(timer);timer=null;if(ctx){try{ctx.close()}catch{}}ctx=null;master=null;panner=null;setStatus('MUTED');const b=$('audioToggle');if(b){b.classList.remove('active');b.textContent='HEAR GLASS'}}
function bind(snapshot){if(!snapshot||snapshot.schema!=='axm.code.grammar-glass-visual-snapshot.v1')return;S=snapshot;dbg.loaded=true;lastPlan=null;if(playing){stop();setStatus('READY')}}
function inspect(){const plan=buildPlan();if(!plan)return;if($('inspector'))$('inspector').textContent=JSON.stringify({sonificationPlan:plan,orchestra:{mode:currentMode(),touchPan:touchPan(),replayChimeCoupling:true,motionPauseCoupling:true},truth:'Interpretive audio mapping only. Sound creates no evidence and is not a correctness signal.'},null,2)}
async function syncMotion(){if(!ctx||!playing)return;const b=$('motionToggle'),paused=!!(b&&(b.textContent==='PLAY'||b.getAttribute('aria-pressed')==='false'));motionPaused=paused;dbg.motionPaused=paused;dbg.motionPauseCoupling=true;clearTimeout(timer);timer=null;if(paused){await ctx.suspend?.();setStatus('ORCHESTRA PAUSED')}else{await ctx.resume?.();setStatus('ORCHESTRA');cycle()}}
function setup(){const toggle=$('audioToggle'),vol=$('audioVolume'),inspectBtn=$('audioInspect'),motion=$('motionToggle');if(toggle)toggle.onclick=()=>playing?stop():start();if(vol)vol.oninput=()=>{if(master)master.gain.value=volume();const e=$('audioVolumeValue');if(e)e.textContent=`${vol.value}%`};if(inspectBtn)inspectBtn.onclick=inspect;if(motion)motion.addEventListener('click',()=>setTimeout(syncMotion,0));addEventListener('axm:grammar-glass-touch-changed',syncPan);addEventListener('axm:grammar-glass-probe-changed',()=>{if(playing&&!motionPaused){clearTimeout(timer);timer=setTimeout(cycle,80)}});addEventListener('axm:grammar-glass-replay-focus',e=>replayChime(e.detail?.event));addEventListener('axm:grammar-glass-snapshot-loaded',e=>bind(e.detail?.snapshot));if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);setStatus('MUTED')}
window.AXMGrammarGlassAudio=Object.freeze({bind,start,stop,getPlan:()=>lastPlan||buildPlan(),getState:()=>({...dbg,touchPan:touchPan(),mode:currentMode()}),contract:Object.freeze({audioCreatesEvidence:false,audioIsCorrectnessSignal:false,cycleMutation:false,orchestraIsInterpretive:true,motionPauseStopsScheduling:true,authority:'NONE'})});setup();
})();
