(()=>{'use strict';
const Core=window.AXMGrammarGlassPlaygroundCore,$=id=>document.getElementById(id);let S=null,probe=null,selected=[],mode='GRAVITY_WELL',strength=.72,roll=0,raf=0,start=0;
const dbg=window.__GRAMMAR_GLASS_PLAYGROUND_STATE__={loaded:false,active:false,mode,selectedGrammarCount:0,probeSha256:null,visualProbeCreatesEvidence:false,cycleMutationPerformed:false,executionRequested:false,darkMatterIsPhysicsClaim:false,authority:'NONE'};
const edgeColor={TYPED_COMPATIBILITY:'#5ee7ff',ANALOGY:'#b89aff',CONTRAST:'#ffc86b',REPULSION:'#ff728f',BOUNDARY:'#70a8ff',UNRESOLVED_NEIGHBOURHOOD:'#8fa4bc'};
const darkClasses=new Set(['CONTRAST','REPULSION','BOUNDARY','UNRESOLVED_NEIGHBOURHOOD']);
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function seedUnit(index=0){if(!probe)return 0;const hex=probe.probeSha256.slice((index*6)%58,(index*6)%58+6);return parseInt(hex||'0',16)/0xffffff}
function vessel(){return window.AXMGrammarGlassVesselView}
function pointFor(atomId){const p=vessel()?.getAtomPoint?.(atomId);return p&&Number.isFinite(p.x)&&Number.isFinite(p.y)?p:null}
function anchor(w,h){if(vessel()&&typeof vessel().getFormationAnchor==='function'&&selected.length){const p=vessel().getFormationAnchor(selected);if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))return p}return{x:w/2,y:h*.46}}
function ring(ctx,x,y,r,d,alpha=.5){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle='#b89aff';ctx.globalAlpha=alpha;ctx.lineWidth=Math.max(1,d*.8);ctx.shadowColor='#b89aff';ctx.shadowBlur=14*d;ctx.stroke();ctx.restore()}
function node(ctx,x,y,label,d,accent='#7df6be'){ctx.save();ctx.beginPath();ctx.arc(x,y,3.2*d,0,Math.PI*2);ctx.fillStyle=accent;ctx.shadowColor=accent;ctx.shadowBlur=12*d;ctx.fill();ctx.font=`${Math.max(8,9*d)}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.78;ctx.fillText(label,x+6*d,y-5*d);ctx.restore()}
function drawGravity(ctx,w,h,d,t,a){const pulse=1+Math.sin(t*2.1)*.08,base=(22+strength*36)*d;for(let i=0;i<4;i++)ring(ctx,a.x,a.y,base*pulse+i*15*d,d,.5-i*.08);ctx.save();ctx.beginPath();ctx.arc(a.x,a.y,(7+strength*7)*d,0,Math.PI*2);ctx.fillStyle='#b89aff';ctx.globalAlpha=.24;ctx.shadowColor='#b89aff';ctx.shadowBlur=26*d;ctx.fill();ctx.restore();selected.forEach((lang,i)=>{const u=seedUnit(i),ang=t*(.35+.25*u)+i/Math.max(1,selected.length)*Math.PI*2+u*2.4,r=(45+u*28+strength*24)*d,x=a.x+Math.cos(ang)*r,y=a.y+Math.sin(ang)*r*.56;ctx.save();ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(a.x,a.y);ctx.strokeStyle='#5ee7ff';ctx.globalAlpha=.12+.18*strength;ctx.lineWidth=d;ctx.stroke();ctx.restore();node(ctx,x,y,lang,d,i%2?'#7df6be':'#5ee7ff')})}
function topologyLine(ctx,a,b,color,d,alpha=.38,dash=[]){ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=color;ctx.globalAlpha=alpha;ctx.lineWidth=Math.max(1,d);ctx.setLineDash(dash.map(v=>v*d));ctx.shadowColor=color;ctx.shadowBlur=6*d;ctx.stroke();ctx.restore()}
function drawTopology(ctx,d,t,darkOnly=false){if(!probe)return 0;let count=0;for(const edge of probe.relationRefs||[]){if(darkOnly&&!darkClasses.has(edge.connectionClass))continue;const a=pointFor(edge.leftAtomId),b=pointFor(edge.rightAtomId);if(!a||!b)continue;const color=edgeColor[edge.connectionClass]||'#8fa4bc';topologyLine(ctx,a,b,color,d,(darkOnly?.34:.22)+(.12*strength),edge.crossGrammar?[3,4]:[]);if(darkOnly){const q=(t*.18+count*.071)%1,x=a.x+(b.x-a.x)*q,y=a.y+(b.y-a.y)*q;ctx.save();ctx.beginPath();ctx.arc(x,y,2.4*d,0,Math.PI*2);ctx.fillStyle=color;ctx.shadowColor=color;ctx.shadowBlur=10*d;ctx.fill();ctx.restore()}count++}if(darkOnly)for(const path of probe.memoryPathRefs||[]){const pts=(path.pathAtomIds||[]).map(pointFor).filter(Boolean);for(let i=1;i<pts.length;i++)topologyLine(ctx,pts[i-1],pts[i],'#7df6be',d,.16+.12*strength,[5,5])}return count}
function drawRift(ctx,w,h,d,t,a){const count=drawTopology(ctx,d,t,false);if(!count){for(let i=0;i<8;i++){const u=seedUnit(i),ang=i/8*Math.PI*2+u*.6,len=(35+u*75)*d;topologyLine(ctx,a,{x:a.x+Math.cos(ang)*len,y:a.y+Math.sin(ang)*len*.55},i%2?'#ffc86b':'#70a8ff',d,.24)}}ring(ctx,a.x,a.y,(28+strength*24)*d,d,.25)}
function drawDarkMatter(ctx,w,h,d,t,a){const count=drawTopology(ctx,d,t,true),pulse=1+Math.sin(t*.9)*.12;ctx.save();ctx.beginPath();ctx.arc(a.x,a.y,(18+Math.min(46,count)*.7)*d*pulse,0,Math.PI*2);ctx.strokeStyle='#8fa4bc';ctx.globalAlpha=.38;ctx.setLineDash([3*d,6*d]);ctx.shadowColor='#b89aff';ctx.shadowBlur=20*d;ctx.stroke();ctx.restore();ctx.save();ctx.font=`${10*d}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.55;ctx.fillText(`DARK GRAMMAR · ${count} unresolved/tension relations`,a.x+18*d,a.y+18*d);ctx.restore()}
function drawStarHunt(ctx,w,h,d,t,a){const count=Math.max(1,Math.min(16,probe?.metrics?.draftStarCount||selected.length));for(let i=0;i<count;i++){const u=seedUnit(i+51),ang=t*(.22+.16*u)+i/count*Math.PI*2,r=(32+u*86+strength*22)*d,x=a.x+Math.cos(ang)*r,y=a.y+Math.sin(ang)*r*.52;ctx.save();ctx.beginPath();ctx.arc(x,y,(1.8+u*2.4)*d,0,Math.PI*2);ctx.fillStyle='#edf5ff';ctx.shadowColor=i%2?'#b89aff':'#5ee7ff';ctx.shadowBlur=14*d;ctx.fill();ctx.globalAlpha=.16;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(x,y);ctx.strokeStyle=ctx.shadowColor;ctx.stroke();ctx.restore()}selected.forEach((lang,i)=>{const ang=-t*.28+i/Math.max(1,selected.length)*Math.PI*2,r=(50+seedUnit(i+79)*25)*d;node(ctx,a.x+Math.cos(ang)*r,a.y+Math.sin(ang)*r*.5,lang,d,'#d7ff8a')})}
function frame(now){const c=$('playgroundCanvas');if(!c)return;const[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(probe){const t=(now-start)/1000,a=anchor(w,h);if(mode==='GRAVITY_WELL')drawGravity(ctx,w,h,d,t,a);else if(mode==='RIFT_SCAN')drawRift(ctx,w,h,d,t,a);else if(mode==='DARK_MATTER')drawDarkMatter(ctx,w,h,d,t,a);else drawStarHunt(ctx,w,h,d,t,a)}raf=requestAnimationFrame(frame)}
function renderMetrics(){const root=$('playgroundMetrics');if(!root)return;if(!probe){root.innerHTML='<div class="playground-empty">Choose grammars or roll a reproducible set. Nothing is written back to the Twister.</div>';return}const m=probe.metrics;root.innerHTML=[['grammars',m.selectedGrammarCount],['atoms',m.selectedAtomCount],['relations',m.relationEdgeCount],['direct carries',m.directCarryCount],['memory paths',m.memoryPathCount],['draft stars',m.draftStarCount]].map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}
function renderChips(){const root=$('playgroundLanguages');if(!root||!S)return;const langs=Core.availableLanguages(S);root.innerHTML=langs.map(id=>`<button class="grammar-chip${selected.includes(id)?' selected':''}" data-lang="${esc(id)}">${esc(id)}</button>`).join('');root.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{const id=b.dataset.lang;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<8)selected=[...selected,id];renderChips();rebuild()})}
function announceProbe(){dispatchEvent(new CustomEvent('axm:grammar-glass-probe-changed',{detail:{probeSha256:probe?.probeSha256||null,probe,mode,languageIds:[...selected]}}))}
function renderStatus(){const el=$('playgroundStatus');if(el)el.textContent=probe?`${mode.replaceAll('_',' ')} · ${selected.length} GRAMMARS`:'IDLE';const warp=$('playgroundWarpValue');if(warp)warp.textContent=`${Math.round(strength*100)}%`;dbg.active=!!probe;dbg.mode=mode;dbg.selectedGrammarCount=selected.length;dbg.probeSha256=probe?.probeSha256||null}
function rebuild(){try{probe=selected.length?Core.createProbe(S,{languageIds:selected,mode,strength,roll}):null;renderMetrics();renderStatus();announceProbe();if(probe&&$('inspector'))$('inspector').textContent=JSON.stringify({playgroundProbe:probe,truth:mode==='DARK_MATTER'?'Dark Grammar is a viewer metaphor for recorded unresolved/tension structure, not a claim about cosmological dark matter.':'Visual playground receipt only. The loaded snapshot remains the recorded evidence source.'},null,2)}catch(error){probe=null;renderMetrics();renderStatus();announceProbe();if($('inspector'))$('inspector').textContent=error.message}}
function selectMode(next){mode=next;document.querySelectorAll('[data-playground-mode]').forEach(b=>b.classList.toggle('active',b.dataset.playgroundMode===mode));rebuild()}
function bind(snapshot){if(!Core.validSnapshot(snapshot))return;S=snapshot;selected=[];probe=null;roll=0;dbg.loaded=true;renderChips();renderMetrics();renderStatus();announceProbe();start=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)}
function exportReceipt(){if(!probe)return;const blob=new Blob([JSON.stringify(probe,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`grammar-glass-probe-${probe.probeSha256.slice(0,12)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function setup(){document.querySelectorAll('[data-playground-mode]').forEach(b=>b.onclick=()=>selectMode(b.dataset.playgroundMode));const rollButton=$('playgroundRoll');if(rollButton)rollButton.onclick=()=>{if(!S)return;roll++;selected=Core.rollLanguages(S,{count:5,roll});renderChips();rebuild()};const clear=$('playgroundClear');if(clear)clear.onclick=()=>{selected=[];probe=null;renderChips();renderMetrics();renderStatus();announceProbe()};const inspect=$('playgroundInspect');if(inspect)inspect.onclick=()=>probe&&$('inspector')&&($('inspector').textContent=JSON.stringify(probe,null,2));const exp=$('playgroundExport');if(exp)exp.onclick=exportReceipt;const warp=$('playgroundWarp');if(warp)warp.oninput=()=>{strength=Math.max(0,Math.min(1,Number(warp.value||72)/100));rebuild()};const f=$('file');if(f)f.addEventListener('change',async e=>{try{const file=e.target.files&&e.target.files[0],loader=window.AXMGrammarGlassSnapshotLoader;if(file)bind(loader?await loader.parse(file):JSON.parse(await file.text()))}catch{}});if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);start=performance.now();raf=requestAnimationFrame(frame)}
window.AXMGrammarGlassPlayground=Object.freeze({bind,getProbe:()=>probe,getState:()=>({...dbg,languageIds:[...selected]}),contract:Object.freeze({visualProbeCreatesEvidence:false,darkMatterIsPhysicsClaim:false,cycleMutation:false,executionAuthority:false,ranking:false,automaticReentry:false})});setup();
})();
