(()=>{'use strict';
const Core=window.AXMGrammarGlassPlaygroundCore,$=id=>document.getElementById(id);let S=null,probe=null,selected=[],mode='GRAVITY_WELL',strength=.72,roll=0,raf=0,start=0;
const dbg=window.__GRAMMAR_GLASS_PLAYGROUND_STATE__={loaded:false,active:false,mode,selectedGrammarCount:0,probeSha256:null,visualProbeCreatesEvidence:false,cycleMutationPerformed:false,executionRequested:false,authority:'NONE'};
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function short(v,n=16){v=String(v||'');return v.length>n?v.slice(0,n)+'…':v||'—'}
function seedUnit(index=0){if(!probe)return 0;const hex=probe.probeSha256.slice((index*6)%58,(index*6)%58+6);return parseInt(hex||'0',16)/0xffffff}
function anchor(w,h){const v=window.AXMGrammarGlassVesselView;if(v&&typeof v.getFormationAnchor==='function'&&selected.length){const p=v.getFormationAnchor(selected);if(p&&Number.isFinite(p.x)&&Number.isFinite(p.y))return p}return{x:w/2,y:h*.46}}
function ring(ctx,x,y,r,d,alpha=.5){ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.strokeStyle='#b89aff';ctx.globalAlpha=alpha;ctx.lineWidth=Math.max(1,d*.8);ctx.shadowColor='#b89aff';ctx.shadowBlur=14*d;ctx.stroke();ctx.restore()}
function node(ctx,x,y,label,d,accent='#7df6be'){ctx.save();ctx.beginPath();ctx.arc(x,y,3.2*d,0,Math.PI*2);ctx.fillStyle=accent;ctx.shadowColor=accent;ctx.shadowBlur=12*d;ctx.fill();ctx.font=`${Math.max(8,9*d)}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.78;ctx.fillText(label,x+6*d,y-5*d);ctx.restore()}
function drawGravity(ctx,w,h,d,t,a){const pulse=1+Math.sin(t*2.1)*.08,base=(22+strength*36)*d;for(let i=0;i<4;i++)ring(ctx,a.x,a.y,base*pulse+i*15*d,d,.5-i*.08);ctx.save();ctx.beginPath();ctx.arc(a.x,a.y,(7+strength*7)*d,0,Math.PI*2);ctx.fillStyle='#b89aff';ctx.globalAlpha=.24;ctx.shadowColor='#b89aff';ctx.shadowBlur=26*d;ctx.fill();ctx.restore();selected.forEach((lang,i)=>{const u=seedUnit(i),ang=t*(.35+.25*u)+i/Math.max(1,selected.length)*Math.PI*2+u*2.4,r=(45+u*28+strength*24)*d,x=a.x+Math.cos(ang)*r,y=a.y+Math.sin(ang)*r*.56;ctx.save();ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(a.x,a.y);ctx.strokeStyle='#5ee7ff';ctx.globalAlpha=.12+.18*strength;ctx.lineWidth=d;ctx.stroke();ctx.restore();node(ctx,x,y,lang,d,i%2?'#7df6be':'#5ee7ff')})}
function drawRift(ctx,w,h,d,t,a){const classes=probe?.metrics?.connectionClassCounts||{},count=Math.max(5,Math.min(18,Object.values(classes).reduce((s,v)=>s+Number(v||0),0)||selected.length*2));for(let i=0;i<count;i++){const u=seedUnit(i),ang=i/count*Math.PI*2+u*.7+t*.04*(i%2?1:-1),len=(30+u*95+strength*28)*d;ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);let x=a.x,y=a.y;for(let k=1;k<=5;k++){const q=k/5,bend=(seedUnit(i+k+13)-.5)*18*d,x2=a.x+Math.cos(ang)*len*q+Math.sin(ang)*bend,y2=a.y+Math.sin(ang)*len*q*.58-Math.cos(ang)*bend*.55;ctx.lineTo(x2,y2);x=x2;y=y2}ctx.strokeStyle=i%3===0?'#ff728f':i%3===1?'#ffc86b':'#70a8ff';ctx.globalAlpha=.22+.25*strength;ctx.lineWidth=(.8+u*.7)*d;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=8*d;ctx.stroke();ctx.restore()}selected.forEach((lang,i)=>{const ang=i/Math.max(1,selected.length)*Math.PI*2-t*.18,r=(48+seedUnit(i+31)*40)*d;node(ctx,a.x+Math.cos(ang)*r,a.y+Math.sin(ang)*r*.58,lang,d,'#ffc86b')})}
function drawStarHunt(ctx,w,h,d,t,a){const count=Math.max(1,Math.min(16,probe?.metrics?.draftStarCount||selected.length));for(let i=0;i<count;i++){const u=seedUnit(i+51),ang=t*(.22+.16*u)+i/count*Math.PI*2,r=(32+u*86+strength*22)*d,x=a.x+Math.cos(ang)*r,y=a.y+Math.sin(ang)*r*.52;ctx.save();ctx.beginPath();ctx.arc(x,y,(1.8+u*2.4)*d,0,Math.PI*2);ctx.fillStyle='#edf5ff';ctx.shadowColor=i%2?'#b89aff':'#5ee7ff';ctx.shadowBlur=14*d;ctx.fill();ctx.globalAlpha=.16;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(x,y);ctx.strokeStyle=ctx.shadowColor;ctx.stroke();ctx.restore()}selected.forEach((lang,i)=>{const ang=-t*.28+i/Math.max(1,selected.length)*Math.PI*2,r=(50+seedUnit(i+79)*25)*d;node(ctx,a.x+Math.cos(ang)*r,a.y+Math.sin(ang)*r*.5,lang,d,'#d7ff8a')})}
function frame(now){const c=$('playgroundCanvas');if(!c)return;const[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(probe){const t=(now-start)/1000,a=anchor(w,h);if(mode==='GRAVITY_WELL')drawGravity(ctx,w,h,d,t,a);else if(mode==='RIFT_SCAN')drawRift(ctx,w,h,d,t,a);else drawStarHunt(ctx,w,h,d,t,a)}raf=requestAnimationFrame(frame)}
function renderMetrics(){const root=$('playgroundMetrics');if(!root)return;if(!probe){root.innerHTML='<div class="playground-empty">Choose grammars or roll a reproducible set. Nothing is written back to the Twister.</div>';return}const m=probe.metrics;root.innerHTML=[['grammars',m.selectedGrammarCount],['atoms',m.selectedAtomCount],['relations',m.relationEdgeCount],['direct carries',m.directCarryCount],['memory paths',m.memoryPathCount],['draft stars',m.draftStarCount]].map(([k,v])=>`<div><span>${esc(k)}</span><b>${esc(v)}</b></div>`).join('')}
function renderChips(){const root=$('playgroundLanguages');if(!root||!S)return;const langs=Core.availableLanguages(S);root.innerHTML=langs.map(id=>`<button class="grammar-chip${selected.includes(id)?' selected':''}" data-lang="${esc(id)}">${esc(id)}</button>`).join('');root.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{const id=b.dataset.lang;if(selected.includes(id))selected=selected.filter(x=>x!==id);else if(selected.length<8)selected=[...selected,id];renderChips();rebuild()})}
function renderStatus(){const el=$('playgroundStatus');if(el)el.textContent=probe?`${mode.replaceAll('_',' ')} · ${selected.length} GRAMMARS`:'IDLE';const warp=$('playgroundWarpValue');if(warp)warp.textContent=`${Math.round(strength*100)}%`;dbg.active=!!probe;dbg.mode=mode;dbg.selectedGrammarCount=selected.length;dbg.probeSha256=probe?.probeSha256||null}
function rebuild(){try{probe=selected.length?Core.createProbe(S,{languageIds:selected,mode,strength,roll}):null;renderMetrics();renderStatus();if(probe&&$('inspector'))$('inspector').textContent=JSON.stringify({playgroundProbe:probe,truth:'Visual playground receipt only. The loaded snapshot remains the recorded evidence source.'},null,2)}catch(error){probe=null;renderMetrics();renderStatus();if($('inspector'))$('inspector').textContent=error.message}}
function selectMode(next){mode=next;document.querySelectorAll('[data-playground-mode]').forEach(b=>b.classList.toggle('active',b.dataset.playgroundMode===mode));rebuild()}
function bind(snapshot){if(!Core.validSnapshot(snapshot))return;S=snapshot;selected=[];probe=null;roll=0;dbg.loaded=true;renderChips();renderMetrics();renderStatus();start=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(frame)}
function exportReceipt(){if(!probe)return;const blob=new Blob([JSON.stringify(probe,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`grammar-glass-probe-${probe.probeSha256.slice(0,12)}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function setup(){document.querySelectorAll('[data-playground-mode]').forEach(b=>b.onclick=()=>selectMode(b.dataset.playgroundMode));const rollButton=$('playgroundRoll');if(rollButton)rollButton.onclick=()=>{if(!S)return;roll++;selected=Core.rollLanguages(S,{count:5,roll});renderChips();rebuild()};const clear=$('playgroundClear');if(clear)clear.onclick=()=>{selected=[];probe=null;renderChips();renderMetrics();renderStatus()};const inspect=$('playgroundInspect');if(inspect)inspect.onclick=()=>probe&&$('inspector')&&($('inspector').textContent=JSON.stringify(probe,null,2));const exp=$('playgroundExport');if(exp)exp.onclick=exportReceipt;const warp=$('playgroundWarp');if(warp)warp.oninput=()=>{strength=Math.max(0,Math.min(1,Number(warp.value||72)/100));rebuild()};const f=$('file');if(f)f.addEventListener('change',async e=>{try{const file=e.target.files&&e.target.files[0];if(file)bind(JSON.parse(await file.text()))}catch{}});if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);start=performance.now();raf=requestAnimationFrame(frame)}
window.AXMGrammarGlassPlayground=Object.freeze({bind,getProbe:()=>probe,getState:()=>({...dbg}),contract:Object.freeze({visualProbeCreatesEvidence:false,cycleMutation:false,executionAuthority:false,ranking:false,automaticReentry:false})});setup();
})();
