(()=>{'use strict';
const Ext=window.AXMGrammarGlassPlaygroundExtensionsCore,$=id=>document.getElementById(id);
let S=null,enabled=false,drag=false,forceMode='PULL',receipt=null,focus={xNorm:.5,yNorm:.5},lastInput='NONE',gamepadTimer=0;
const buttonLatch=new Map();
const reduceMotion=window.matchMedia?window.matchMedia('(prefers-reduced-motion: reduce)'):null;
const dbg=window.__GRAMMAR_GLASS_TOUCH_STATE__={loaded:false,enabled:false,dragging:false,forceMode,receiptSha256:null,pointerMotionCreatesEvidence:false,cycleMutationPerformed:false,staleProbeAutoClears:true,keyboardNavigation:true,gamepadNavigation:true,lastInput,focusX:.5,focusY:.5,authority:'NONE'};
const frameLayer=window.AXMGrammarGlassFrameSteward.registerLayer('touch-lens',{mode:'CONTINUOUS',draw});
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function currentProbe(){return window.AXMGrammarGlassPlayground&&window.AXMGrammarGlassPlayground.getProbe?window.AXMGrammarGlassPlayground.getProbe():null}
function setStatus(text){const e=$('touchStatus');if(e)e.textContent=text}
function setFeedback(text){const e=$('touchFeedback');if(e)e.textContent=text}
function announce(){dispatchEvent(new CustomEvent('axm:grammar-glass-touch-changed',{detail:{receipt,focus:{...focus},forceMode,enabled,lastInput}}))}
function syncDebug(){dbg.enabled=enabled;dbg.dragging=drag;dbg.forceMode=forceMode;dbg.receiptSha256=receipt?.touchReceiptSha256||null;dbg.lastInput=lastInput;dbg.focusX=focus.xNorm;dbg.focusY=focus.yNorm}
function syncFrame(){const c=$('touchCanvas');if(!enabled&&!receipt){frameLayer.sleep();if(c)c.getContext('2d').clearRect(0,0,c.width,c.height);return}if(reduceMotion?.matches){frameLayer.sleep();draw(performance.now());return}frameLayer.activate()}
function clear(reason='',keepEnabled=true){receipt=null;drag=false;if(!keepEnabled)enabled=false;syncDebug();setStatus(enabled?(reason||'ARMED'):'OFF');setFeedback(enabled?`AIM ${Math.round(focus.xNorm*100)}·${Math.round(focus.yNorm*100)} · ARROWS/WASD MOVE · ENTER APPLY · F FLIP`:'ARM TOUCH LENS · POINTER, KEYBOARD OR GAMEPAD');syncFrame();announce()}
function point(event){const wrap=$('fieldWrap'),r=wrap.getBoundingClientRect();return{xNorm:Math.max(0,Math.min(1,(event.clientX-r.left)/Math.max(1,r.width))),yNorm:Math.max(0,Math.min(1,(event.clientY-r.top)/Math.max(1,r.height)))}}
function strengthValue(){return Math.max(0,Math.min(1,Number($('touchStrength')?.value||70)/100))}
function setFocus(next,source='AIM'){focus={xNorm:Math.max(0,Math.min(1,Number(next.xNorm)||0)),yNorm:Math.max(0,Math.min(1,Number(next.yNorm)||0))};lastInput=source;receipt=null;syncDebug();setStatus(enabled?`AIM · ${Math.round(focus.xNorm*100)}·${Math.round(focus.yNorm*100)}`:'OFF');setFeedback(enabled?`AIM ${Math.round(focus.xNorm*100)}·${Math.round(focus.yNorm*100)} · ENTER/A APPLY · F/X FLIP · B RESET`:'ARM TOUCH LENS · POINTER, KEYBOARD OR GAMEPAD');syncFrame();announce()}
function rebuildAt(next,source='POINTER'){const probe=currentProbe();if(!enabled||!S||!probe)return;focus={xNorm:Math.max(0,Math.min(1,Number(next.xNorm)||0)),yNorm:Math.max(0,Math.min(1,Number(next.yNorm)||0))};const strength=strengthValue();lastInput=source;try{receipt=Ext.createTouchReceipt(S,probe,{...focus,forceMode,strength});syncDebug();setStatus(`${forceMode} · ${Math.round(strength*100)}% · ${source}`);setFeedback(`${forceMode} @ ${Math.round(focus.xNorm*100)}·${Math.round(focus.yNorm*100)} · VISUAL ONLY · RECORDED COORDINATES UNCHANGED`);announce();syncFrame();if($('inspector'))$('inspector').textContent=JSON.stringify({touchLens:receipt,input:{source,focus:{...focus},forceMode},truth:'Pointer, keyboard and gamepad input bend the rendered vessel projection only. Recorded atom/cycle state is unchanged.'},null,2)}catch(error){receipt=null;syncDebug();setStatus('HELD');setFeedback(`HELD · ${error.message}`);if($('inspector'))$('inspector').textContent=error.message;syncFrame()}}
function draw(now=performance.now()){const c=$('touchCanvas');if(!c)return;const[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(!enabled&&!receipt)return;const x=focus.xNorm*w,y=focus.yNorm*h,s=receipt?.focus?.strength??strengthValue(),pull=(receipt?.focus?.forceMode||forceMode)==='PULL',color=pull?'#5ee7ff':'#ff728f',accent=pull?'#7df6be':'#ffc86b',motion=reduceMotion?.matches?0:Math.sin(now/180)*.08,pulse=1+motion;
ctx.save();ctx.translate(x,y);ctx.strokeStyle=color;ctx.fillStyle=accent;ctx.shadowColor=color;ctx.shadowBlur=14*d;ctx.globalAlpha=enabled?.9:.6;ctx.lineWidth=Math.max(1,d);const arm=11*d,gap=7*d;ctx.beginPath();ctx.moveTo(-gap-arm,-gap);ctx.lineTo(-gap,-gap);ctx.lineTo(-gap,-gap-arm);ctx.moveTo(gap+arm,-gap);ctx.lineTo(gap,-gap);ctx.lineTo(gap,-gap-arm);ctx.moveTo(-gap-arm,gap);ctx.lineTo(-gap,gap);ctx.lineTo(-gap,gap+arm);ctx.moveTo(gap+arm,gap);ctx.lineTo(gap,gap);ctx.lineTo(gap,gap+arm);ctx.stroke();ctx.beginPath();ctx.arc(0,0,2.4*d,0,Math.PI*2);ctx.fill();ctx.restore();
if(receipt){for(let i=0;i<4;i++){ctx.save();ctx.beginPath();ctx.arc(x,y,(16+i*15+s*28)*d*pulse,0,Math.PI*2);ctx.strokeStyle=color;ctx.globalAlpha=.42-i*.08;ctx.lineWidth=Math.max(1,d);ctx.shadowColor=color;ctx.shadowBlur=16*d;ctx.stroke();ctx.restore()}ctx.save();ctx.beginPath();ctx.arc(x,y,(5+s*7)*d,0,Math.PI*2);ctx.fillStyle=accent;ctx.shadowColor=accent;ctx.shadowBlur=24*d;ctx.fill();ctx.restore();const langs=receipt.languageIds||[];langs.forEach((lang,i)=>{const a=i/Math.max(1,langs.length)*Math.PI*2+(reduceMotion?.matches?0:now/1800*(pull?1:-1)),r=(48+i%3*14+s*25)*d,x2=x+Math.cos(a)*r,y2=y+Math.sin(a)*r*.55;ctx.save();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x,y);ctx.strokeStyle=color;ctx.globalAlpha=.12+.15*s;ctx.stroke();ctx.font=`${9*d}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.68;ctx.fillText(String(lang).slice(0,8),x2+4*d,y2-4*d);ctx.restore()})}
ctx.save();ctx.font=`700 ${Math.max(9,9*d)}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.72;ctx.fillText(`${forceMode} · ${Math.round(s*100)}%`,Math.min(w-120*d,x+16*d),Math.max(16*d,y-16*d));ctx.restore()}
function bind(snapshot){if(!snapshot||snapshot.schema!=='axm.code.grammar-glass-visual-snapshot.v1')return;S=snapshot;dbg.loaded=true;clear(enabled?'ARMED':'',true)}
function onProbeChanged(event){const next=event?.detail?.probeSha256||null;if(receipt&&receipt.probeSha256!==next)clear('REBOUND')}
function toggleMode(){forceMode=forceMode==='PULL'?'PUSH':'PULL';lastInput='MODE';syncDebug();const modeButton=$('touchForce');if(modeButton)modeButton.textContent=forceMode;if(receipt)clear('RE-APPLY');else{setStatus(enabled?forceMode:'OFF');setFeedback(enabled?`${forceMode} READY · ENTER/A APPLY`:'ARM TOUCH LENS · POINTER, KEYBOARD OR GAMEPAD');syncFrame()}}
function adjustStrength(delta){const slider=$('touchStrength');if(!slider)return;slider.value=String(Math.max(Number(slider.min||0),Math.min(Number(slider.max||100),Number(slider.value||70)+delta)));lastInput='STRENGTH';receipt=null;syncDebug();setStatus(enabled?`AIM · ${slider.value}%`:'OFF');setFeedback(enabled?`VISUAL FORCE ${slider.value}% · ENTER/A APPLY`:'ARM TOUCH LENS · POINTER, KEYBOARD OR GAMEPAD');syncFrame();announce()}
function moveFocus(dx,dy,source){setFocus({xNorm:focus.xNorm+dx,yNorm:focus.yNorm+dy},source)}
function onKey(event){if(!enabled)return;const key=event.key.toLowerCase(),step=event.shiftKey?.1:.035;let handled=true;if(key==='arrowleft'||key==='a')moveFocus(-step,0,'KEYBOARD');else if(key==='arrowright'||key==='d')moveFocus(step,0,'KEYBOARD');else if(key==='arrowup'||key==='w')moveFocus(0,-step,'KEYBOARD');else if(key==='arrowdown'||key==='s')moveFocus(0,step,'KEYBOARD');else if(key==='enter'||key===' ')rebuildAt(focus,'KEYBOARD');else if(key==='f')toggleMode();else if(key==='[')adjustStrength(-5);else if(key===']')adjustStrength(5);else if(key==='escape')clear('RESET');else handled=false;if(handled){event.preventDefault();event.stopPropagation()}}
function gamepadEdge(index,pressed){const prior=buttonLatch.get(index)===true;buttonLatch.set(index,pressed===true);return pressed===true&&!prior}
function pollGamepad(){if(!enabled||document.hidden||typeof navigator.getGamepads!=='function')return;const pad=[...(navigator.getGamepads()||[])].find(Boolean);if(!pad)return;const ax=Number(pad.axes?.[0]||0),ay=Number(pad.axes?.[1]||0),dead=.42;if(Math.abs(ax)>dead||Math.abs(ay)>dead){moveFocus(Math.abs(ax)>dead?Math.sign(ax)*.025:0,Math.abs(ay)>dead?Math.sign(ay)*.025:0,'GAMEPAD')}if(gamepadEdge(0,pad.buttons?.[0]?.pressed))rebuildAt(focus,'GAMEPAD');if(gamepadEdge(2,pad.buttons?.[2]?.pressed))toggleMode();if(gamepadEdge(1,pad.buttons?.[1]?.pressed))clear('RESET');if(gamepadEdge(4,pad.buttons?.[4]?.pressed))adjustStrength(-5);if(gamepadEdge(5,pad.buttons?.[5]?.pressed))adjustStrength(5)}
function injectExperience(){if(!$('touchExperienceStyle')){const style=document.createElement('style');style.id='touchExperienceStyle';style.textContent=`#fieldWrap.touch-lens-armed{cursor:crosshair;outline:1px solid rgba(94,231,255,.28);outline-offset:-2px}#fieldWrap.touch-lens-armed:focus-visible{outline:2px solid rgba(125,246,190,.88);box-shadow:inset 0 0 0 3px rgba(125,246,190,.08),0 0 28px rgba(94,231,255,.14)}.touch-feedback{margin:.45rem 0;padding:.42rem .5rem;border:1px solid rgba(94,231,255,.16);border-radius:8px;background:rgba(4,10,18,.52);font:700 9px/1.35 ui-monospace,monospace;letter-spacing:.035em;color:#dceeff}.instrument-card:focus-within .touch-feedback{border-color:rgba(125,246,190,.4);box-shadow:0 0 16px rgba(94,231,255,.08)}@media(prefers-reduced-motion:reduce){#fieldWrap.touch-lens-armed{scroll-behavior:auto}}`;document.head.appendChild(style)}if(!$('touchFeedback')){const note=document.querySelector('.touch-note'),el=document.createElement('div');el.id='touchFeedback';el.className='touch-feedback';el.setAttribute('role','status');el.setAttribute('aria-live','polite');el.textContent='ARM TOUCH LENS · POINTER, KEYBOARD OR GAMEPAD';if(note)note.before(el)}}
function setEnabled(next){enabled=!!next;drag=false;lastInput='TOGGLE';const wrap=$('fieldWrap'),toggle=$('touchToggle');if(toggle){toggle.classList.toggle('active',enabled);toggle.textContent=enabled?'TOUCH ARMED':'TOUCH LENS';toggle.setAttribute('aria-pressed',String(enabled))}if(wrap){wrap.classList.toggle('touch-lens-armed',enabled);if(enabled){wrap.tabIndex=0;wrap.setAttribute('aria-label','Grammar Glass touch lens. Arrow keys or WASD move the visual focus, Enter applies, F flips pull or push.');try{wrap.focus({preventScroll:true})}catch{wrap.focus()}}else{wrap.removeAttribute('tabindex');wrap.removeAttribute('aria-label')}}if(!enabled)clear('',false);else{syncDebug();setStatus('ARMED · INPUT READY');setFeedback('AIM 50·50 · ARROWS/WASD MOVE · ENTER APPLY · F FLIP · [ ] FORCE');syncFrame();announce()}}
function setup(){injectExperience();const wrap=$('fieldWrap'),toggle=$('touchToggle'),mode=$('touchForce'),reset=$('touchReset'),slider=$('touchStrength');if(toggle){toggle.setAttribute('aria-pressed','false');toggle.setAttribute('aria-keyshortcuts','Enter Space');toggle.onclick=()=>setEnabled(!enabled)}if(mode){mode.setAttribute('aria-keyshortcuts','F');mode.onclick=toggleMode}if(reset)reset.onclick=()=>clear('RESET');if(slider)slider.oninput=()=>{receipt=null;lastInput='SLIDER';syncDebug();setStatus(enabled?`AIM · ${slider.value}%`:'OFF');setFeedback(enabled?`VISUAL FORCE ${slider.value}% · ENTER/A APPLY`:'ARM TOUCH LENS · POINTER, KEYBOARD OR GAMEPAD');syncFrame();announce()};if(wrap){wrap.addEventListener('keydown',onKey);wrap.addEventListener('pointerdown',e=>{if(!enabled)return;drag=true;dbg.dragging=true;wrap.setPointerCapture?.(e.pointerId);const p=point(e);focus=p;rebuildAt(p,'POINTER');e.preventDefault()});wrap.addEventListener('pointermove',e=>{if(enabled&&drag){const p=point(e);focus=p;rebuildAt(p,'POINTER')}});wrap.addEventListener('pointerup',e=>{if(!enabled)return;drag=false;syncDebug();wrap.releasePointerCapture?.(e.pointerId)});wrap.addEventListener('pointercancel',()=>{drag=false;syncDebug()})}addEventListener('axm:grammar-glass-probe-changed',onProbeChanged);addEventListener('axm:grammar-glass-snapshot-loaded',e=>bind(e.detail?.snapshot));if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);reduceMotion?.addEventListener?.('change',syncFrame);gamepadTimer=window.setInterval(pollGamepad,80)}
window.AXMGrammarGlassTouchLens=Object.freeze({bind,clear,getReceipt:()=>receipt,getState:()=>({...dbg,focus:{...focus}}),contract:Object.freeze({pointerMotionCreatesEvidence:false,keyboardMotionCreatesEvidence:false,gamepadMotionCreatesEvidence:false,cycleMutation:false,staleProbeAutoClears:true,executionAuthority:false})});setup();
})();
