(()=>{'use strict';
const Ext=window.AXMGrammarGlassPlaygroundExtensionsCore,$=id=>document.getElementById(id);let S=null,ctx=null,master=null,timer=null,playing=false,lastPlan=null;
const dbg=window.__GRAMMAR_GLASS_AUDIO_STATE__={loaded:false,playing:false,planSha256:null,eventCount:0,audioCreatesEvidence:false,audioIsCorrectnessSignal:false,authority:'NONE'};
function currentProbe(){return window.AXMGrammarGlassPlayground&&window.AXMGrammarGlassPlayground.getProbe?window.AXMGrammarGlassPlayground.getProbe():null}
function setStatus(v){const e=$('audioStatus');if(e)e.textContent=v}
function volume(){return Math.max(0,Math.min(.3,Number($('audioVolume')?.value||12)/100))}
function tone(event,at){if(!ctx||!master)return;const osc=ctx.createOscillator(),gain=ctx.createGain(),now=at+event.offsetMs/1000,dur=Math.max(.04,event.durationMs/1000),g=Math.min(.08,Number(event.gain||.015));osc.frequency.setValueAtTime(Number(event.frequency||220),now);osc.type=event.kind==='DIRECT_CARRY_PULSE'?'square':event.kind==='CONTACT_MEMORY_ECHO'?'triangle':'sine';gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(Math.max(.0002,g),now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+dur);osc.connect(gain);gain.connect(master);osc.start(now);osc.stop(now+dur+.03)}
function buildPlan(){const probe=currentProbe();if(!S||!probe)return null;try{return Ext.createSonificationPlan(S,probe,{density:.62})}catch{return null}}
function cycle(){if(!playing||!ctx)return;const plan=buildPlan();if(!plan){setStatus('SELECT GRAMMARS');return}lastPlan=plan;dbg.planSha256=plan.sonificationPlanSha256;dbg.eventCount=plan.events.length;const at=ctx.currentTime+.05;plan.events.forEach(e=>tone(e,at));setStatus(`PLAYING · ${plan.events.length}`);const span=Math.max(1200,...plan.events.map(e=>e.offsetMs+e.durationMs))+420;clearTimeout(timer);timer=setTimeout(cycle,span)}
async function start(){if(playing)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC){setStatus('NO WEB AUDIO');return}ctx=new AC();await ctx.resume();master=ctx.createGain();master.gain.value=volume();master.connect(ctx.destination);playing=true;dbg.playing=true;const b=$('audioToggle');if(b){b.classList.add('active');b.textContent='STOP SOUND'}cycle()}
function stop(){playing=false;dbg.playing=false;clearTimeout(timer);timer=null;if(ctx){try{ctx.close()}catch{}}ctx=null;master=null;setStatus('MUTED');const b=$('audioToggle');if(b){b.classList.remove('active');b.textContent='HEAR GLASS'}}
function bind(snapshot){if(!snapshot||snapshot.schema!=='axm.code.grammar-glass-visual-snapshot.v1')return;S=snapshot;dbg.loaded=true;lastPlan=null;if(playing){stop();setStatus('READY')}}
function inspect(){const plan=buildPlan();if(!plan)return;if($('inspector'))$('inspector').textContent=JSON.stringify({sonificationPlan:plan,truth:'Interpretive audio mapping only. Sound creates no evidence and is not a correctness signal.'},null,2)}
function setup(){const toggle=$('audioToggle'),vol=$('audioVolume'),inspectBtn=$('audioInspect');if(toggle)toggle.onclick=()=>playing?stop():start();if(vol)vol.oninput=()=>{if(master)master.gain.value=volume();const e=$('audioVolumeValue');if(e)e.textContent=`${vol.value}%`};if(inspectBtn)inspectBtn.onclick=inspect;const f=$('file');if(f)f.addEventListener('change',async e=>{try{const file=e.target.files&&e.target.files[0];if(file)bind(JSON.parse(await file.text()))}catch{}});if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);setStatus('MUTED')}
window.AXMGrammarGlassAudio=Object.freeze({bind,start,stop,getPlan:()=>lastPlan||buildPlan(),getState:()=>({...dbg}),contract:Object.freeze({audioCreatesEvidence:false,audioIsCorrectnessSignal:false,cycleMutation:false,authority:'NONE'})});setup();
})();
