(()=>{'use strict';
const Ext=window.AXMGrammarGlassPlaygroundExtensionsCore,$=id=>document.getElementById(id);let S=null,enabled=false,drag=false,forceMode='PULL',receipt=null,raf=0;
const dbg=window.__GRAMMAR_GLASS_TOUCH_STATE__={loaded:false,enabled:false,dragging:false,forceMode,receiptSha256:null,pointerMotionCreatesEvidence:false,cycleMutationPerformed:false,authority:'NONE'};
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function currentProbe(){return window.AXMGrammarGlassPlayground&&window.AXMGrammarGlassPlayground.getProbe?window.AXMGrammarGlassPlayground.getProbe():null}
function setStatus(text){const e=$('touchStatus');if(e)e.textContent=text}
function clear(){receipt=null;drag=false;dbg.dragging=false;dbg.receiptSha256=null;setStatus(enabled?'ARMED':'OFF')}
function point(event){const wrap=$('fieldWrap'),r=wrap.getBoundingClientRect();return{xNorm:Math.max(0,Math.min(1,(event.clientX-r.left)/Math.max(1,r.width))),yNorm:Math.max(0,Math.min(1,(event.clientY-r.top)/Math.max(1,r.height)))}}
function rebuild(event){const probe=currentProbe();if(!enabled||!S||!probe)return;const p=point(event),strength=Math.max(0,Math.min(1,Number($('touchStrength')?.value||70)/100));try{receipt=Ext.createTouchReceipt(S,probe,{...p,forceMode,strength});dbg.receiptSha256=receipt.touchReceiptSha256;setStatus(`${forceMode} · ${Math.round(strength*100)}%`);if($('inspector'))$('inspector').textContent=JSON.stringify({touchLens:receipt,truth:'Pointer movement bends only the visual lens. Recorded atom/cycle state is unchanged.'},null,2)}catch(error){setStatus('HELD');if($('inspector'))$('inspector').textContent=error.message}}
function draw(){const c=$('touchCanvas');if(!c){raf=requestAnimationFrame(draw);return}const[w,h,d]=fit(c),ctx=c.getContext('2d');ctx.clearRect(0,0,w,h);if(receipt){const x=receipt.focus.xNorm*w,y=receipt.focus.yNorm*h,s=receipt.focus.strength,pull=receipt.focus.forceMode==='PULL',pulse=1+Math.sin(performance.now()/180)*.08;for(let i=0;i<4;i++){ctx.save();ctx.beginPath();ctx.arc(x,y,(16+i*15+s*28)*d*pulse,0,Math.PI*2);ctx.strokeStyle=pull?'#5ee7ff':'#ff728f';ctx.globalAlpha=.45-i*.08;ctx.lineWidth=Math.max(1,d);ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=16*d;ctx.stroke();ctx.restore()}ctx.save();ctx.beginPath();ctx.arc(x,y,(5+s*7)*d,0,Math.PI*2);ctx.fillStyle=pull?'#7df6be':'#ffc86b';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=24*d;ctx.fill();ctx.restore();const probe=currentProbe(),langs=probe?.languageIds||[];langs.forEach((lang,i)=>{const a=i/Math.max(1,langs.length)*Math.PI*2+performance.now()/1800*(pull?1:-1),r=(48+i%3*14+s*25)*d,x2=x+Math.cos(a)*r,y2=y+Math.sin(a)*r*.55;ctx.save();ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x,y);ctx.strokeStyle=pull?'#5ee7ff':'#ff728f';ctx.globalAlpha=.15+.18*s;ctx.stroke();ctx.font=`${9*d}px ui-monospace,monospace`;ctx.fillStyle='#edf5ff';ctx.globalAlpha=.75;ctx.fillText(String(lang).slice(0,8),x2+4*d,y2-4*d);ctx.restore()})}raf=requestAnimationFrame(draw)}
function bind(snapshot){if(!snapshot||snapshot.schema!=='axm.code.grammar-glass-visual-snapshot.v1')return;S=snapshot;dbg.loaded=true;clear()}
function setup(){const wrap=$('fieldWrap'),toggle=$('touchToggle'),mode=$('touchForce'),reset=$('touchReset');if(toggle)toggle.onclick=()=>{enabled=!enabled;dbg.enabled=enabled;toggle.classList.toggle('active',enabled);toggle.textContent=enabled?'TOUCH ARMED':'TOUCH LENS';setStatus(enabled?'ARMED':'OFF');if(!enabled)clear()};if(mode)mode.onclick=()=>{forceMode=forceMode==='PULL'?'PUSH':'PULL';dbg.forceMode=forceMode;mode.textContent=forceMode;setStatus(enabled?forceMode:'OFF')};if(reset)reset.onclick=clear;if(wrap){wrap.addEventListener('pointerdown',e=>{if(!enabled)return;drag=true;dbg.dragging=true;wrap.setPointerCapture?.(e.pointerId);rebuild(e)});wrap.addEventListener('pointermove',e=>{if(enabled&&drag)rebuild(e)});wrap.addEventListener('pointerup',e=>{if(!enabled)return;drag=false;dbg.dragging=false;wrap.releasePointerCapture?.(e.pointerId)});wrap.addEventListener('pointercancel',()=>{drag=false;dbg.dragging=false})}const f=$('file');if(f)f.addEventListener('change',async e=>{try{const file=e.target.files&&e.target.files[0];if(file)bind(JSON.parse(await file.text()))}catch{}});if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
window.AXMGrammarGlassTouchLens=Object.freeze({bind,clear,getReceipt:()=>receipt,getState:()=>({...dbg}),contract:Object.freeze({pointerMotionCreatesEvidence:false,cycleMutation:false,executionAuthority:false})});setup();
})();
