(()=>{'use strict';
const Core=window.AXMGrammarGlassFrameStewardCore,Steward=window.AXMGrammarGlassFrameSteward,$=id=>document.getElementById(id);let receipt=null,busy=false;
const dbg=window.__GRAMMAR_GLASS_PULSE_CHECK__={installed:!!(Core&&Steward),busy:false,runCount:0,lastResult:null,lastReceiptSha256:null,telemetrySent:false,automaticRenderTierChange:false,authority:'NONE'};
function status(text,state=''){const e=$('pulseStatus');if(e){e.textContent=text;e.dataset.state=state}}
function metrics(){const root=$('pulseMetrics');if(!root)return;if(!receipt){root.innerHTML='<div><span>STATE</span><b>READY TO SAMPLE</b></div><div><span>RNG PATH</span><b>PRESERVED</b></div>';return}const m=receipt.metrics;root.innerHTML=[['P50 FRAME',m.p50FrameMs==null?'—':`${m.p50FrameMs} ms`],['P95 FRAME',m.p95FrameMs==null?'—':`${m.p95FrameMs} ms`],['MAX FRAME',m.maxFrameMs==null?'—':`${m.maxFrameMs} ms`],['> 50 MS',m.framesOver50Ms],['ACTIVE LAYERS',m.activeLayerCount],['SAMPLES',m.sampleCount]].map(([a,b])=>`<div><span>${a}</span><b>${b}</b></div>`).join('')}
function longFrameObserver(){const values=[];if(!window.PerformanceObserver||!PerformanceObserver.supportedEntryTypes?.includes('long-animation-frame'))return{values,stop(){}};try{const observer=new PerformanceObserver(list=>{for(const entry of list.getEntries())if(Number.isFinite(entry.duration))values.push(entry.duration)});observer.observe({type:'long-animation-frame',buffered:false});return{values,stop(){observer.disconnect()}}}catch{return{values,stop(){}}}}
async function run(){if(busy||!window.GRAMMAR_GLASS_SNAPSHOT)return;busy=true;dbg.busy=true;const runBtn=$('pulseRun'),exportBtn=$('pulseExport');if(runBtn)runBtn.disabled=true;if(exportBtn)exportBtn.disabled=true;status('SAMPLING · 5S','SAMPLING');const loaf=longFrameObserver();try{const raw=await Steward.observe(5000);loaf.stop();receipt=Core.createPulseReceipt({...raw,longFrameDurationsMs:loaf.values,snapshot:window.GRAMMAR_GLASS_SNAPSHOT});dbg.runCount++;dbg.lastResult=receipt.result;dbg.lastReceiptSha256=receipt.pulseReceiptSha256;metrics();status(receipt.metrics.p95FrameMs==null?'HELD · NO FRAMES':`P95 ${receipt.metrics.p95FrameMs} MS · ${receipt.metrics.framesOver50Ms} LONG`,'READY');if($('inspector'))$('inspector').textContent=JSON.stringify({localFramePulse:receipt,truth:'Local projection timing only. Seeded combination exploration is preserved; unfamiliar does not by itself mean novel, correct, safe, or promotable.'},null,2)}catch(error){loaf.stop();status(`HELD · ${error.message}`,'HELD')}finally{busy=false;dbg.busy=false;if(runBtn)runBtn.disabled=!window.GRAMMAR_GLASS_SNAPSHOT;if(exportBtn)exportBtn.disabled=!receipt}}
function exportReceipt(){if(!receipt)return;const blob=new Blob([JSON.stringify(receipt,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`grammar-glass-frame-pulse-${receipt.pulseReceiptSha256.slice(0,12)}.json`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
function inspect(){if(receipt&&$('inspector'))$('inspector').textContent=JSON.stringify(receipt,null,2)}
function bind(){const runBtn=$('pulseRun');if(runBtn)runBtn.disabled=false;status('READY · LOCAL','READY')}
$('pulseRun')?.addEventListener('click',run);$('pulseExport')?.addEventListener('click',exportReceipt);$('pulseInspect')?.addEventListener('click',inspect);addEventListener('axm:grammar-glass-snapshot-loaded',bind);if(window.GRAMMAR_GLASS_SNAPSHOT)bind();metrics();
window.AXMGrammarGlassPulseCheck=Object.freeze({run,getReceipt:()=>receipt,getState:()=>({...dbg}),contract:Object.freeze({localOnly:true,telemetrySent:false,automaticRenderTierChange:false,seededExplorationPreserved:true,authority:'NONE'})});
})();
