(()=>{'use strict';
const api={};
const truth=Object.freeze({inspectOnly:true,projectionCreatesEvidence:false,starContainsExecutableSoftware:false,automaticExecution:false,automaticReentry:false,automaticPromotion:false,comparisonRanks:false});
const store=()=>window.AXMGrammarGlassHistoryStore;
const view=()=>window.AXMGrammarGlassExecutionHistoryView;
const snapshot=()=>store()?.getSnapshot?.()||window.GRAMMAR_GLASS_SNAPSHOT||null;
const stars=()=>view()?.getStars?.()||[];
const byDigest=d=>stars().find(s=>s.digest===d)||null;
const val=(v,f=null)=>v===undefined||v===null||v===''?f:v;
function context(star){const s=snapshot()||{},m=s.interglass?.candidateModel||{},r=s.interglass?.runRequest||{};const draftDigest=star.kind==='DRAFT'?star.digest:star.draftStarSha256;return{rootSeed:s.rootSeed||null,dayStartSha256:s.dayStartSha256||null,conditionDigest:s.cycle?.conditionSha256||null,cycleStep:val(star.data?.cycleStep,s.cycle?.tick??null),profileCount:s.profileCount??null,atomCount:s.atomCount??null,candidateBound:m.draftStarSha256===draftDigest,candidateModelDigest:m.candidateModelDigest||null,formationDigest:m.formationDigest||star.data?.formationDigest||null,formationSeed:m.formationSeed||star.data?.formationSeed||null,executorClass:r.executorProfile?.enforcementClass||null,networkMode:r.executorProfile?.networkMode||null,maxAttempts:r.resourceCeilings?.maxAttempts??null,saveSlotCount:r.sandboxContractBinding?.saveSlotCount??null,maxBytesPerSaveSlot:r.sandboxContractBinding?.maxBytesPerSaveSlot??null,interglassState:s.interglass?.state||null,sourceMode:s.sourceMode||null}}
function captured(star,key){const d=star.data||{};if(Object.prototype.hasOwnProperty.call(d,key)&&d[key]!==null&&d[key]!==undefined&&d[key]!=='')return{value:d[key],origin:'CAPTURED RECEIPT'};return null}
function bound(ctx,key){const v=ctx[key];return v===null||v===undefined||v===''?null:{value:v,origin:'BOUND SNAPSHOT CONTEXT'} }
function field(star,ctx,key,ctxKey=key){return captured(star,key)||bound(ctx,ctxKey)||{value:null,origin:'NOT RECORDED'}}
function mirrorText(star){const s=snapshot(),m=s?.interglass?.candidateModel;if(!m)return null;const draft=star.kind==='DRAFT'?star.digest:star.draftStarSha256;if(m.draftStarSha256!==draft)return null;const rs=(s.mirrorResponses||[]);return rs.find(x=>x.formationSha256===m.formationDigest)?.lines?.join('\n')||rs[0]?.lines?.join('\n')||null}
function replayAudit(star,ctx){const req=Array.isArray(star.data?.replayRequirements)?star.data.replayRequirements:[];const checks=[['root seed',!!(star.data?.rootSeed||ctx.rootSeed)],['condition',!!(star.data?.conditionDigest||ctx.conditionDigest)],['cycle step',Number.isFinite(Number(star.data?.cycleStep??ctx.cycleStep))],['grammar identities',(star.languageIds||star.data?.languageIds||[]).length>0],['receipt digest',!!star.digest],['candidate binding',star.kind==='DRAFT'?ctx.candidateBound:!!(star.data?.candidateModelDigest||ctx.candidateModelDigest)],['request digest',star.kind==='RUN'?!!star.data?.requestSha256:true],['executor binding',star.kind==='RUN'?!!(star.data?.executorProfileDigest||ctx.executorClass):true],['explicit replay requirements',req.length>0]];const present=checks.filter(([,ok])=>ok).length;return{checks:checks.map(([name,ok])=>({name,ok})),present,total:checks.length,ratio:checks.length?present/checks.length:0,result:'REPLAY_INPUT_AUDIT_ONLY_NOT_EXECUTION_PERMISSION',replayRequestState:store()?.replayHold||'EXPLICIT_REPLAY_REQUEST_HELD_EXECUTOR_AND_USER_ACTION_REQUIRED'}}
function lineage(star,ctx){const parent=star.kind==='RUN'?byDigest(star.draftStarSha256):star;return{stages:[{id:'FORMATION',active:true,digest:ctx.formationDigest||star.data?.formationDigest||null,origin:ctx.formationDigest?'BOUND SNAPSHOT CONTEXT':'CAPTURED/UNKNOWN'},{id:'DRAFT',active:true,digest:parent?.digest||star.draftStarSha256||star.digest,origin:'CAPTURED RECEIPT'},{id:'CANDIDATE',active:ctx.candidateBound||star.kind==='RUN',digest:star.data?.candidateModelDigest||ctx.candidateModelDigest||null,origin:star.data?.candidateModelDigest?'CAPTURED RECEIPT':'BOUND SNAPSHOT CONTEXT'},{id:'INNER GLASS',active:star.kind==='RUN',digest:star.data?.executorProfileDigest||null,origin:star.data?.executorProfileDigest?'CAPTURED RECEIPT':'BOUND SNAPSHOT CONTEXT'},{id:'RESULT',active:star.kind==='RUN',digest:star.data?.resultModelDigest||star.data?.observationSha256||null,origin:'CAPTURED RECEIPT'}],parentDraft:parent||null}}
function model(star){if(!star)return null;const ctx=context(star),d=star.data||{},run=star.kind==='RUN';const fields={digest:{value:star.digest,origin:'CAPTURED RECEIPT'},kind:{value:star.kind,origin:'DERIVED VIEW'},source:{value:star.source,origin:'CAPTURED RECEIPT'},resultClass:{value:run?star.resultClass:'DRAFT_CAPTURED',origin:'CAPTURED RECEIPT'},cycleStep:field(star,ctx,'cycleStep'),rootSeed:field(star,ctx,'rootSeed'),conditionDigest:field(star,ctx,'conditionDigest'),dayStartSha256:field(star,ctx,'dayStartSha256'),draftStarSha256:{value:run?star.draftStarSha256:star.digest,origin:'CAPTURED RECEIPT'},candidateModelDigest:field(star,ctx,'candidateModelDigest'),formationDigest:field(star,ctx,'formationDigest'),formationSeed:field(star,ctx,'formationSeed'),requestSha256:field(star,ctx,'requestSha256'),observationSha256:field(star,ctx,'observationSha256'),resultModelDigest:field(star,ctx,'resultModelDigest'),runtimePayloadDigest:field(star,ctx,'runtimePayloadDigest'),executorProfileDigest:field(star,ctx,'executorProfileDigest'),attempt:field(star,ctx,'attempt'),networkAttemptBlocked:field(star,ctx,'networkAttemptBlocked'),opaqueOriginObserved:field(star,ctx,'opaqueOriginObserved')};return{star,ctx,fields,grammars:d.languageIds||star.languageIds||[],atomTypes:d.atomTypes||[],connectionClasses:d.connectionClasses||[],replayRequirements:d.replayRequirements||[],mirrorText:mirrorText(star),replayAudit:replayAudit(star,ctx),lineage:lineage(star,ctx),raw:{kind:star.kind,source:star.source,resultClass:star.resultClass,digest:star.digest,draftStarSha256:star.draftStarSha256,data:d,truth},truth}}
function compare(a,b){const A=model(a),B=model(b);if(!A||!B)return null;const keys=['kind','source','resultClass','cycleStep','rootSeed','conditionDigest','draftStarSha256','candidateModelDigest','formationDigest','requestSha256','resultModelDigest','executorProfileDigest'];const rows=keys.map(k=>({field:k,a:A.fields[k]?.value??null,b:B.fields[k]?.value??null,same:String(A.fields[k]?.value??'')===String(B.fields[k]?.value??'')}));const ga=new Set(A.grammars),gb=new Set(B.grammars);return{a:A,b:B,rows,grammarOverlap:[...ga].filter(x=>gb.has(x)),onlyA:[...ga].filter(x=>!gb.has(x)),onlyB:[...gb].filter(x=>!ga.has(x)),result:'NON_RANKING_CAPTURE_COMPARISON',winner:null,qualityScore:null,truth}}
Object.assign(api,{snapshot,stars,byDigest,model,compare,truth});
window.AXMGrammarGlassStarZoomData=Object.freeze(api);
})();
