(()=>{'use strict';
const data=window.AXMGrammarGlassStarZoomData;if(!data)return;
const CONTRACT=Object.freeze({mode:'STARZOOM_CAPTURE_LENS_V2',inspectOnly:true,visualProjectionCreatesEvidence:false,starContainsExecutableSoftware:false,automaticReentry:false,automaticExecution:false,compareRanks:false});
let current=null,pinned=null,overlay=null,lastFocus=null,origin={x:'50%',y:'50%'},activeTab='CAPTURE';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const short=(v,n=18)=>v?String(v).slice(0,n)+'…':'—';
const color=r=>r==='PASS_OBSERVED'?'#7df6be':r==='HELD'?'#ffc86b':r==='FAIL_OBSERVED'?'#ff728f':r==='CRASH_OBSERVED'?'#ff8c71':r==='TIMEOUT_OBSERVED'?'#70a8ff':'#b89aff';
const debug=window.__GRAMMAR_GLASS_STARZOOM_STATE__={open:false,starKind:null,resultClass:null,digest:null,parentDraftStarSha256:null,activeTab:'CAPTURE',pinnedDigest:null,compareActive:false,inspectOnly:true,projectionCreatesEvidence:false,openCount:0,closeCount:0};
function view(){return window.AXMGrammarGlassExecutionHistoryView}
function stars(){return data.stars()}
function byDigest(d){return data.byDigest(d)}
function originBadge(o){const c=o==='CAPTURED RECEIPT'?'captured':o==='BOUND SNAPSHOT CONTEXT'?'context':'derived';return`<span class="starzoom-origin ${c}">${esc(o)}</span>`}
function dl(rows){return`<dl class="starzoom-grid">${rows.filter(x=>x&&x.value!==null&&x.value!==undefined&&x.value!=='').map(x=>`<dt>${esc(x.label)}</dt><dd>${esc(Array.isArray(x.value)?x.value.join(' · '):x.value)} ${originBadge(x.origin||'DERIVED VIEW')}</dd>`).join('')}</dl>`}
function chips(items=[],origin='CAPTURED RECEIPT'){return items.length?`<div class="starzoom-list">${items.map(x=>`<span class="starzoom-chip">${esc(x)}</span>`).join('')} ${originBadge(origin)}</div>`:'<div class="starzoom-empty">none recorded</div>'}
function fieldRows(m,keys){return keys.map(k=>({label:k,value:m.fields[k]?.value,origin:m.fields[k]?.origin}))}
function captureTab(m){const run=m.star.kind==='RUN';return[`<section class="starzoom-section"><h3>${run?'CAPTURED RUN RECEIPT':'CAPTURED DRAFT RECEIPT'}</h3>${dl(fieldRows(m,run?['digest','source','resultClass','cycleStep','rootSeed','conditionDigest','dayStartSha256','draftStarSha256','candidateModelDigest','requestSha256','observationSha256','resultModelDigest','runtimePayloadDigest','executorProfileDigest','attempt','networkAttemptBlocked','opaqueOriginObserved']:['digest','source','cycleStep','rootSeed','conditionDigest','dayStartSha256','formationDigest','formationSeed','candidateModelDigest']))}</section>`,`<section class="starzoom-section"><h3>CONTRIBUTING GRAMMARS</h3>${chips(m.grammars)}</section>`,!run?`<section class="starzoom-section"><h3>STRUCTURAL CAPTURE</h3>${dl([{label:'atom types',value:m.atomTypes.join(' · '),origin:'CAPTURED RECEIPT'},{label:'connection classes',value:m.connectionClasses.join(' · '),origin:'CAPTURED RECEIPT'}])}</section>`:'',m.mirrorText?`<section class="starzoom-section"><h3>BOUND MIRROR CAPTURE</h3><pre class="starzoom-capture-lines">${esc(m.mirrorText)}</pre>${originBadge('BOUND SNAPSHOT CONTEXT')}</section>`:''].join('')}
function lineageTab(m){const stages=m.lineage.stages.map(s=>`<div class="starzoom-lineage-stage" data-active="${s.active?'true':'false'}"><b>${esc(s.id)}</b><small>${esc(short(s.digest,26))}</small>${originBadge(s.origin)}</div>`).join('');const parent=m.star.kind==='RUN'&&m.lineage.parentDraft?`<button class="starzoom-link" data-open-digest="${esc(m.lineage.parentDraft.digest)}">ZOOM PARENT DRAFT STAR ↗</button>`:'';return`<section class="starzoom-section"><h3>CAPTURE LINEAGE</h3><div class="starzoom-lineage-map">${stages}</div><div class="starzoom-section-actions">${parent}<button class="starzoom-link" id="starZoomFocusVessel">FOCUS LINEAGE IN VESSEL</button></div></section><section class="starzoom-section"><h3>LINEAGE TRUTH</h3><div class="starzoom-note">The path visualizes recorded/bound identities. A visual connection is not an independent proof of correctness, usefulness, or causality beyond the receipt relationships.</div></section>`}
function replayTab(m){const a=m.replayAudit,checks=a.checks.map(x=>`<div class="starzoom-check" data-ok="${x.ok?'true':'false'}"><i>${x.ok?'✓':'×'}</i><span>${esc(x.name)}</span></div>`).join('');return`<section class="starzoom-section"><h3>REPLAY INPUT AUDIT</h3><div class="starzoom-readiness"><b>${a.present}/${a.total}</b><span>required identity/input classes visible</span><div class="starzoom-readiness-bar"><i style="width:${Math.round(a.ratio*100)}%"></i></div></div><div class="starzoom-checks">${checks}</div></section><section class="starzoom-section"><h3>REPLAY REQUIREMENTS</h3>${chips(m.replayRequirements)}</section><section class="starzoom-section"><h3>REPLAY STATE</h3>${dl([{label:'audit result',value:a.result,origin:'DERIVED VIEW'},{label:'request state',value:a.replayRequestState,origin:'CAPTURED/BOUND POLICY'}])}<div class="starzoom-note warning">Replay readiness is not permission to execute and does not prove the real world will reproduce the same outcome.</div></section>`}
function compareTab(){if(!pinned||!current)return`<section class="starzoom-section"><h3>COMPARE TWO CAPTURES</h3><div class="starzoom-empty padded">Pin a star, then browse to another star. Comparison is non-ranking and never chooses a winner.</div></section>`;const c=data.compare(pinned,current);const rows=c.rows.map(r=>`<tr data-same="${r.same?'true':'false'}"><th>${esc(r.field)}</th><td>${esc(r.a??'—')}</td><td>${esc(r.b??'—')}</td></tr>`).join('');return`<section class="starzoom-section"><h3>NON-RANKING CAPTURE COMPARISON</h3><div class="starzoom-compare-head"><div><span>PINNED</span><b>${esc(short(pinned.digest,18))}</b></div><div><span>CURRENT</span><b>${esc(short(current.digest,18))}</b></div></div><div class="starzoom-compare-wrap"><table class="starzoom-compare"><thead><tr><th>field</th><th>A</th><th>B</th></tr></thead><tbody>${rows}</tbody></table></div></section><section class="starzoom-section"><h3>GRAMMAR OVERLAP</h3>${dl([{label:'shared',value:c.grammarOverlap.join(' · ')||'none',origin:'DERIVED VIEW'},{label:'only pinned',value:c.onlyA.join(' · ')||'none',origin:'DERIVED VIEW'},{label:'only current',value:c.onlyB.join(' · ')||'none',origin:'DERIVED VIEW'}])}<div class="starzoom-note">No winner, score, preference, or automatic selection is calculated.</div></section>`}
function rawTab(m){return`<section class="starzoom-section"><h3>EXACT RECEIPT VIEW</h3><pre class="starzoom-raw-block">${esc(JSON.stringify(m.raw,null,2))}</pre></section>`}
function chain(m){return m.lineage.stages.map(s=>`<div class="starzoom-node" data-active="${s.active?'true':'false'}">${esc(s.id)}</div>`).join('')}
function ensure(){if(overlay)return;overlay=document.createElement('div');overlay.className='starzoom-overlay';overlay.id='starZoomOverlay';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.innerHTML=`<div class="starzoom-shell"><div class="starzoom-lens"><div class="starzoom-lens-title"><div class="eyebrow" id="starZoomEyebrow">STARZOOM</div><h2 id="starZoomLensTitle">CAPTURE LENS</h2><small id="starZoomLensSub"></small></div><div class="starzoom-orbit"></div><div class="starzoom-hero"><span class="starzoom-glyph" id="starZoomGlyph"></span></div><div class="starzoom-chain" id="starZoomChain"></div></div><div class="starzoom-capture"><header class="starzoom-head"><div class="starzoom-head-main"><h2 id="starZoomTitle">Captured event</h2><small id="starZoomDigest"></small></div><div class="starzoom-actions"><button class="starzoom-button" id="starZoomPrev">←</button><button class="starzoom-button" id="starZoomPin">PIN</button><button class="starzoom-button" id="starZoomNext">→</button><button class="starzoom-button starzoom-close" id="starZoomClose">×</button></div></header><nav class="starzoom-tabs" id="starZoomTabs"><button data-tab="CAPTURE">CAPTURE</button><button data-tab="LINEAGE">LINEAGE</button><button data-tab="REPLAY">REPLAY</button><button data-tab="COMPARE">COMPARE</button><button data-tab="RAW">RAW</button></nav><div class="starzoom-body"><div class="starzoom-summary" id="starZoomSummary"></div><div id="starZoomTabBody"></div><div class="starzoom-truth">Inspect-only lens. Stars are evidence/snapshot markers, not executable software and not quality votes. Captured receipt, bound snapshot context, and derived views are labeled separately. Zooming, comparing, and browsing create no evidence or execution authority.</div></div></div></div>`;document.body.appendChild(overlay);$('starZoomClose').onclick=close;$('starZoomPrev').onclick=()=>step(-1);$('starZoomNext').onclick=()=>step(1);$('starZoomPin').onclick=pinCurrent;overlay.addEventListener('click',e=>{if(e.target===overlay)close()});$('starZoomTabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b){activeTab=b.dataset.tab;render(current)}}}
function summary(m){const s=m.star.kind==='DRAFT'?[['TYPE','DRAFT STAR'],['GRAMMARS',m.grammars.length],['CYCLE',m.fields.cycleStep.value??'—']]:[['TYPE','RUN STAR'],['RESULT',m.star.resultClass],['SOURCE',m.star.source]];return s.map(([a,b])=>`<div class="starzoom-kpi"><span>${esc(a)}</span><b>${esc(b)}</b></div>`).join('')}
function tabBody(m){if(activeTab==='LINEAGE')return lineageTab(m);if(activeTab==='REPLAY')return replayTab(m);if(activeTab==='COMPARE')return compareTab();if(activeTab==='RAW')return rawTab(m);return captureTab(m)}
function bindDynamic(){overlay.querySelectorAll('[data-open-digest]').forEach(b=>b.onclick=()=>openByDigest(b.dataset.openDigest));const f=$('starZoomFocusVessel');if(f)f.onclick=()=>{view()?.selectByDigest?.(current.digest);close()}}
function render(star){if(!star)return;ensure();current=star;const m=data.model(star),accent=star.kind==='DRAFT'?'#b89aff':color(star.resultClass);overlay.style.setProperty('--sz-accent',accent);overlay.style.setProperty('--sz-accent-soft',accent+'35');$('starZoomEyebrow').textContent=`STARZOOM · ${star.kind} CAPTURE`;$('starZoomLensTitle').textContent=star.kind==='DRAFT'?'IMMUTABLE DRAFT STAR':star.resultClass;$('starZoomLensSub').textContent=m.grammars.join(' × ')||'no grammar labels recorded';$('starZoomTitle').textContent=star.kind==='DRAFT'?'What this Draft Star captured':'What this Run Star captured';$('starZoomDigest').textContent=star.digest;const g=$('starZoomGlyph');g.dataset.kind=star.kind;g.dataset.result=star.resultClass||'DRAFT_CAPTURED';$('starZoomChain').innerHTML=chain(m);$('starZoomSummary').innerHTML=summary(m);$('starZoomTabBody').innerHTML=tabBody(m);$('starZoomTabs').querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===activeTab));$('starZoomPin').classList.toggle('active',!!pinned&&pinned.digest===star.digest);$('starZoomPin').textContent=pinned?.digest===star.digest?'PINNED':'PIN';bindDynamic();debug.starKind=star.kind;debug.resultClass=star.resultClass;debug.digest=star.digest;debug.parentDraftStarSha256=star.kind==='RUN'?star.draftStarSha256:null;debug.activeTab=activeTab;debug.pinnedDigest=pinned?.digest||null;debug.compareActive=activeTab==='COMPARE'&&!!pinned}
function open(star,point=null){if(!star)return;ensure();lastFocus=document.activeElement;if(point)origin={x:`${point.x}px`,y:`${point.y}px`};overlay.style.setProperty('--sz-origin-x',origin.x);overlay.style.setProperty('--sz-origin-y',origin.y);view()?.selectByDigest?.(star.digest);render(star);overlay.dataset.open='true';document.body.classList.add('starzoom-open');debug.open=true;debug.openCount++;setTimeout(()=>$('starZoomClose')?.focus(),30)}
function close(){if(!overlay||!debug.open)return;overlay.dataset.open='false';document.body.classList.remove('starzoom-open');debug.open=false;debug.closeCount++;setTimeout(()=>{try{lastFocus?.focus?.()}catch{}},40)}
function step(delta){const a=stars();if(!current||!a.length)return;const i=a.findIndex(s=>s.key===current.key);open(a[(i+delta+a.length)%a.length])}
function pinCurrent(){if(!current)return;pinned=pinned?.digest===current.digest?null:current;debug.pinnedDigest=pinned?.digest||null;render(current)}
function openByDigest(d){const s=byDigest(d);if(s)open(s)}
function setTab(t){if(['CAPTURE','LINEAGE','REPLAY','COMPARE','RAW'].includes(t)){activeTab=t;if(current)render(current)}}
window.AXMGrammarGlassStarZoom=Object.freeze({open,openByDigest,close,step,pinCurrent,setTab,getCurrent:()=>current,getPinned:()=>pinned,getState:()=>({...debug}),contract:CONTRACT});
})();
