(()=>{'use strict';
function wait(){if(!window.AXMGrammarGlassStarZoom||!window.AXMGrammarGlassExecutionHistoryView||!document.getElementById('executionSky'))return setTimeout(wait,50);boot()}
function boot(){const zoom=window.AXMGrammarGlassStarZoom,view=window.AXMGrammarGlassExecutionHistoryView,canvas=document.getElementById('executionSky');let tooltip=null,hud=null,lastKey=null,filter='ALL';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const short=(v,n=16)=>v?String(v).slice(0,n)+'…':'—';
function starByKey(k){return(view.getStars?.()||[]).find(s=>s.key===k)||null}
function hit(e){const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height,x=(e.clientX-r.left)*sx,y=(e.clientY-r.top)*sy;let best=null,d=Infinity;for(const h of view.getHitTargets?.()||[]){const q=Math.hypot(h.x-x,h.y-y);if(q<h.r*1.45&&q<d){best=h;d=q}}return best}
function ensureTooltip(){if(tooltip)return;tooltip=document.createElement('div');tooltip.className='starzoom-tooltip';document.body.appendChild(tooltip)}
function showTip(e,h){ensureTooltip();const s=starByKey(h.key);if(!s)return hideTip();tooltip.innerHTML=`<b>${esc(s.kind==='DRAFT'?'DRAFT STAR':s.resultClass)}</b><span>${esc((s.languageIds||[]).slice(0,4).join(' × ')||s.source)}</span><small>${esc(short(s.digest,22))} · click to StarZoom</small>`;tooltip.style.left=`${Math.min(innerWidth-285,e.clientX+14)}px`;tooltip.style.top=`${Math.min(innerHeight-90,e.clientY+14)}px`;tooltip.dataset.show='true';lastKey=s.key}
function hideTip(){if(tooltip)tooltip.dataset.show='false';lastKey=null}
function openHit(e){const h=hit(e);if(!h)return;const s=starByKey(h.key);if(s)zoom.open(s,{x:e.clientX,y:e.clientY})}
canvas.addEventListener('pointermove',e=>{const h=hit(e);h?showTip(e,h):hideTip()});canvas.addEventListener('pointerleave',hideTip);canvas.addEventListener('click',e=>{const h=hit(e);if(h)setTimeout(()=>openHit(e),0)});
function ensureHud(){if(hud)return;const scene=document.getElementById('fieldWrap');if(!scene)return;hud=document.createElement('div');hud.className='starzoom-hud';hud.innerHTML=`<div class="starzoom-hud-head"><b>STAR NAVIGATOR</b><button data-hud-toggle>−</button></div><div class="starzoom-hud-body"><div class="starzoom-hud-filters"><button data-filter="ALL">ALL</button><button data-filter="DRAFT">DRAFT</button><button data-filter="PASS_OBSERVED">PASS</button><button data-filter="FAIL_OBSERVED">FAIL</button><button data-filter="CRASH_OBSERVED">CRASH</button><button data-filter="TIMEOUT_OBSERVED">TIMEOUT</button><button data-filter="HELD">HELD</button></div><div class="starzoom-hud-list"></div><div class="starzoom-hud-help">hover = preview · click = zoom · ←/→ browse · P pin · 1–5 tabs</div></div>`;scene.appendChild(hud);hud.querySelector('[data-hud-toggle]').onclick=()=>{hud.classList.toggle('collapsed');hud.querySelector('[data-hud-toggle]').textContent=hud.classList.contains('collapsed')?'+':'−'};hud.querySelector('.starzoom-hud-filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;renderHud()};hud.querySelector('.starzoom-hud-list').onclick=e=>{const b=e.target.closest('[data-star-key]');if(!b)return;const s=starByKey(b.dataset.starKey);if(s)zoom.open(s)};renderHud()}
function renderHud(){if(!hud)return;const all=view.getStars?.()||[],shown=all.filter(s=>filter==='ALL'||(filter==='DRAFT'?s.kind==='DRAFT':s.resultClass===filter));hud.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));hud.querySelector('.starzoom-hud-list').innerHTML=shown.slice(0,18).map(s=>`<button data-star-key="${esc(s.key)}"><i data-kind="${esc(s.kind)}" data-result="${esc(s.resultClass)}"></i><span><b>${esc(s.kind==='DRAFT'?'DRAFT':s.resultClass.replace('_OBSERVED',''))}</b><small>${esc((s.languageIds||[]).slice(0,2).join(' × ')||short(s.digest,12))}</small></span></button>`).join('')||'<div class="starzoom-hud-empty">no matching captures</div>'}
ensureHud();setInterval(renderHud,1400);
document.addEventListener('keydown',e=>{if(!zoom.getState().open)return;if(e.key==='Escape'){zoom.close();return}if(e.key==='ArrowLeft'){e.preventDefault();zoom.step(-1)}if(e.key==='ArrowRight'){e.preventDefault();zoom.step(1)}if(e.key.toLowerCase()==='p')zoom.pinCurrent();if(e.key==='1')zoom.setTab('CAPTURE');if(e.key==='2')zoom.setTab('LINEAGE');if(e.key==='3')zoom.setTab('REPLAY');if(e.key==='4')zoom.setTab('COMPARE');if(e.key==='5')zoom.setTab('RAW')});
window.__GRAMMAR_GLASS_STARZOOM_STEWARD_STATE__={hoverPreview:true,navigatorHud:true,filters:true,keyboardNavigation:true,inspectOnly:true};}
wait();
})();
