(()=>{'use strict';
let S=null,raf=0,start=0,execState='EMPTY',unsubscribe=null,lastPoints=new Map(),lastCanvas={w:0,h:0,d:1},focus=null;
const $=id=>document.getElementById(id);
const glyph={STATE:'state',CONDITION:'if',TRANSFORMATION:'=>',CONTROL_FLOW:'for',TYPE:'<T>',INTERFACE:'api',EFFECT:'fx',DEPENDENCY:'import',VERIFICATION:'check',FAILURE:'!',REPRESENTATION:'{}'};
const color={STATE:'#5ee7ff',CONDITION:'#7df6be',TRANSFORMATION:'#b89aff',CONTROL_FLOW:'#70a8ff',TYPE:'#ff9fd0',INTERFACE:'#ffc86b',EFFECT:'#ff728f',DEPENDENCY:'#9ad1ff',VERIFICATION:'#d7ff8a',FAILURE:'#ff8c71',REPRESENTATION:'#edf5ff'};
const dbg=window.__GRAMMAR_GLASS_VESSEL_STATE__={loaded:false,frameCount:0,vesselMode:'CYLINDRICAL_HELICAL_CODE_TWISTER',codeFragmentCount:0,formationCondensationVisible:false,candidateTransferState:'EMPTY',visualProjectionCreatesEvidence:false,lineageFocusActive:false,focusLanguageCount:0,selectedStarKind:null,focusAnchorVisible:false};
function fit(c){const d=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.round(r.width*d)),h=Math.max(1,Math.round(r.height*d));if(c.width!==w)c.width=w;if(c.height!==h)c.height=h;return[w,h,d]}
function n(v,f=0){v=Number(v);return Number.isFinite(v)?v:f}
function wrap01(v){v%=1;return v<0?v+1:v}
function shortLang(v){v=String(v||'?');return v.length>5?v.slice(0,5):v}
function focusLanguages(){return new Set(focus&&Array.isArray(focus.languageIds)?focus.languageIds:[])}
function atomPoint(a,i,w,h,t){const N=Math.max(1,S.cycle.atoms.length),cx=w/2,top=h*.095,bottom=h*.845,H=bottom-top;const baseAngle=n(a.position&&a.position.angle)+(n(a.angularVelocityPpm)+n(a.appliedInfluenceCarryPpm)*.28)/1e6*16*t;const phase=wrap01(i/N*1.83+n(a.orbitBand)*.071+n(a.position&&a.position.radius)*.19+t*(.018+Math.abs(n(a.angularVelocityPpm))/9e6));const y=top+phase*H,yn=(y-(top+H/2))/(H/2),throat=.22+.78*Math.pow(Math.min(1,Math.abs(yn)),.72);const depth=(Math.sin(baseAngle)+1)/2,jarHalf=Math.min(w*.265,h*.34),r=jarHalf*throat*(.68+n(a.position&&a.position.radius,.5)*.32);return{x:cx+Math.cos(baseAngle)*r,y,depth,scale:.62+depth*.72,angle:baseAngle,radius:r}}
function drawSeedThreads(ctx,w,h,d,t){const seed=String(S.rootSeed||''),cx=w/2,top=h*.085,throatY=h*.46;for(let k=0;k<3;k++){const v=parseInt(seed.slice(k*4,k*4+4)||'0',16)/65535;ctx.save();ctx.beginPath();for(let s=0;s<=44;s++){const q=s/44,y=top+(throatY-top)*q,x=cx+Math.sin(q*10+t*(.4+k*.09)+v*6.28+k*2.1)*(w*(.025+.008*k))*(1-q*.72);s?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=k===1?'#b89aff55':'#7df6be55';ctx.lineWidth=(1.1+k*.25)*d;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=8*d;ctx.stroke();ctx.restore()}}
function line(ctx,a,b,stroke,d,alpha=.22){ctx.save();ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.strokeStyle=stroke;ctx.globalAlpha=alpha;ctx.lineWidth=d;ctx.stroke();ctx.restore()}
function drawCondensation(ctx,w,h,d,t){const I=S.interglass||{},m=I.candidateModel;if(!m)return;const langs=new Set(m.languageIds||[]),atoms=S.cycle.atoms.filter(a=>langs.has(a.languageId)).slice(0,20);if(!atoms.length)return;dbg.formationCondensationVisible=true;const cx=w/2,cy=h*.465;ctx.save();ctx.globalCompositeOperation='lighter';atoms.forEach((a,i)=>{const ang=i/atoms.length*Math.PI*2+t*.7,r=8*d+(i%5)*3.6*d,x=cx+Math.cos(ang)*r,y=cy+Math.sin(ang*1.7)*r*.48;ctx.beginPath();ctx.arc(x,y,(1.4+(i%3)*.45)*d,0,Math.PI*2);ctx.fillStyle=color[a.atomType]||'#fff';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=14*d;ctx.fill()});ctx.restore();ctx.save();ctx.beginPath();ctx.ellipse(cx,cy,42*d,15*d,t*.08,0,Math.PI*2);ctx.strokeStyle='#7df6be77';ctx.lineWidth=1.2*d;ctx.shadowColor='#7df6be';ctx.shadowBlur=18*d;ctx.stroke();ctx.restore()}
function getFormationAnchor(languageIds=[]){const langs=new Set(Array.isArray(languageIds)?languageIds:[]),fallback={x:lastCanvas.w/2||0,y:(lastCanvas.h||0)*.465};if(!S||!lastPoints.size||!langs.size)return fallback;const targetY=(lastCanvas.h||0)*.465,items=[];for(const atom of S.cycle.atoms){if(!langs.has(atom.languageId))continue;const p=lastPoints.get(atom.atomId);if(!p)continue;const weight=1/(1+Math.abs(p.y-targetY)/(Math.max(1,lastCanvas.h)*.12));items.push({p,weight})}if(!items.length)return fallback;const total=items.reduce((s,v)=>s+v.weight,0);return{x:items.reduce((s,v)=>s+v.p.x*v.weight,0)/total,y:items.reduce((s,v)=>s+v.p.y*v.weight,0)/total}}
function drawFocus(ctx,w,h,d){if(!focus)return;const a=getFormationAnchor(focus.languageIds),pulse=1+Math.sin(performance.now()/190)*.12;ctx.save();ctx.beginPath();ctx.arc(a.x,a.y,18*d*pulse,0,Math.PI*2);ctx.strokeStyle=focus.kind==='RUN'?'#ffc86bcc':'#b89affcc';ctx.lineWidth=1.3*d;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=18*d;ctx.stroke();ctx.restore();dbg.focusAnchorVisible=true}
function drawVortex(now){if(!S)return;const c=$('vesselCanvas');if(!c)return;const [w,h,d]=fit(c),ctx=c.getContext('2d'),t=(now-start)/1000;lastCanvas={w,h,d};ctx.clearRect(0,0,w,h);drawSeedThreads(ctx,w,h,d,t);lastPoints=new Map();const pts=S.cycle.atoms.map((a,i)=>({a,i,p:atomPoint(a,i,w,h,t)})).sort((x,y)=>x.p.depth-y.p.depth);for(const item of pts)lastPoints.set(item.a.atomId,item.p);const carries=(S.cycle.influenceCarries||[]).filter(x=>n(x.signedDeltaPpm)!==0).slice(0,64);for(const e of carries){const a=lastPoints.get(e.sourceAtomId),b=lastPoints.get(e.targetAtomId);if(a&&b)line(ctx,a,b,'#7df6be',d,focus?.languageIds?.length?.24:.12)}const paths=(S.contactMemory&&S.contactMemory.multiHopPaths||[]).slice(0,20);for(const path of paths){const ids=path.pathAtomIds||[];for(let i=1;i<ids.length;i++){const a=lastPoints.get(ids[i-1]),b=lastPoints.get(ids[i]);if(a&&b)line(ctx,a,b,'#b89aff',d,focus?.languageIds?.length?.2:.1)}}const fl=focusLanguages();let labels=0;for(const {a,i,p} of pts){const c0=color[a.atomType]||'#edf5ff',front=p.depth>.48,base=front?2.1:1.25,match=!fl.size||fl.has(a.languageId),dim=focus&&!match?.16:1;ctx.save();ctx.globalAlpha=(.18+p.depth*.72)*dim;ctx.beginPath();ctx.arc(p.x,p.y,base*p.scale*d*(focus&&match?1.35:1),0,Math.PI*2);ctx.fillStyle=c0;ctx.shadowColor=c0;ctx.shadowBlur=focus&&match?(front?16:8)*d:(front?7:2)*d;ctx.fill();if(front&&i%7==0&&(!focus||match)){ctx.font=`${Math.max(7,8*p.scale)*d}px ui-monospace,monospace`;ctx.fillStyle=c0;ctx.globalAlpha=.35+p.depth*.5;ctx.fillText(`${shortLang(a.languageId)}:${glyph[a.atomType]||a.atomType||'atom'}`,p.x+4*d,p.y-3*d);labels++}ctx.restore()}drawCondensation(ctx,w,h,d,t);drawFocus(ctx,w,h,d);dbg.frameCount++;dbg.codeFragmentCount=labels;dbg.candidateTransferState=execState;raf=requestAnimationFrame(drawVortex)}
function setState(state){execState=state||'EMPTY';const tr=$('candidateTransfer'),inner=$('innerGlassVessel');if(tr)tr.dataset.state=execState;if(inner)inner.dataset.state=execState;const label=$('candidateCrystalLabel'),model=S&&S.interglass&&S.interglass.candidateModel;if(label&&model)label.textContent=(model.languageIds||[]).slice(0,2).map(shortLang).join('×')||'candidate'}
function focusLineage(meta={}){focus={kind:meta.kind||'DRAFT',digest:meta.digest||null,resultClass:meta.resultClass||null,languageIds:Array.isArray(meta.languageIds)?meta.languageIds:[]};const scene=$('fieldWrap'),tr=$('candidateTransfer');if(scene)scene.dataset.lineageFocus='true';if(tr)tr.dataset.focus='true';dbg.lineageFocusActive=true;dbg.focusLanguageCount=focus.languageIds.length;dbg.selectedStarKind=focus.kind}
function clearFocus(){focus=null;const scene=$('fieldWrap'),tr=$('candidateTransfer');if(scene)scene.dataset.lineageFocus='false';if(tr)tr.dataset.focus='false';dbg.lineageFocusActive=false;dbg.focusLanguageCount=0;dbg.selectedStarKind=null;dbg.focusAnchorVisible=false}
function bind(s){if(!s||s.schema!=='axm.code.grammar-glass-visual-snapshot.v1'||!s.cycle||!Array.isArray(s.cycle.atoms))return;S=s;dbg.loaded=true;dbg.formationCondensationVisible=false;clearFocus();setState(s.interglass&&s.interglass.state||'CANDIDATE_RECEIVED');cancelAnimationFrame(raf);start=performance.now();raf=requestAnimationFrame(drawVortex);if(unsubscribe)unsubscribe();if(window.AXMInterglassExecutor&&window.AXMInterglassExecutor.on)unsubscribe=window.AXMInterglassExecutor.on(e=>setState(e.state))}
window.AXMGrammarGlassVesselView=Object.freeze({focusLineage,clearFocus,getFormationAnchor,getState:()=>({...dbg,currentExecutionState:execState}),contract:Object.freeze({lineageFocus:'FORMATION_TO_DRAFT_TO_SANDBOX_TO_RUN',projectionCreatesEvidence:false,starCountMeansQuality:false,automaticTwisterReentry:false})});
const f=$('file');if(f)f.addEventListener('change',async e=>{try{const file=e.target.files&&e.target.files[0];if(file)bind(JSON.parse(await file.text()))}catch{}});addEventListener('resize',()=>S&&drawVortex(performance.now()));if(window.GRAMMAR_GLASS_SNAPSHOT)bind(window.GRAMMAR_GLASS_SNAPSHOT);
})();
