(()=>{'use strict';
const Core=window.AXMGrammarGlassWorkbenchCore,$=id=>document.getElementById(id);let last=null,refreshTimer=null;
const dbg=window.__GRAMMAR_GLASS_WORKBENCH_STATE__={installed:false,result:'WORKBENCH_PARTIAL',handoffSha256:null,staleRepairCount:0,keyboardShortcutsScoped:true,exportCreatesEvidence:false,authority:'NONE'};
function short(v,n=8){v=String(v||'');return v?v.slice(0,n):'—'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function installStyle(){if($('workbenchPolishStyles'))return;const s=document.createElement('style');s.id='workbenchPolishStyles';s.textContent=`.gg-workbench{margin:.65rem 0 .15rem;padding:.68rem;border:1px solid rgba(94,231,255,.18);border-radius:12px;background:linear-gradient(180deg,rgba(7,17,29,.82),rgba(3,9,16,.9));box-shadow:inset 0 0 28px rgba(94,231,255,.025)}.gg-workbench:focus{outline:1px solid rgba(125,246,190,.5);outline-offset:2px}.gg-workbench-head{display:flex;align-items:center;justify-content:space-between;gap:.6rem}.gg-workbench-head b{font:800 10px/1 ui-monospace,monospace;letter-spacing:.09em}.gg-workbench-state{font:800 9px/1 ui-monospace,monospace}.gg-workbench-state[data-state="WORKBENCH_READY"]{color:#7df6be}.gg-workbench-state[data-state="HELD_STALE_VIEW_STATE"]{color:#ffba7a}.gg-stage-row{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:.28rem;margin:.55rem 0}.gg-stage{padding:.38rem .3rem;border-radius:8px;border:1px solid rgba(255,255,255,.06);background:rgba(255,255,255,.022);text-align:center}.gg-stage span{display:block;font:600 7px/1.1 ui-monospace,monospace;opacity:.5}.gg-stage b{display:block;margin-top:.18rem;font:800 8px/1 ui-monospace,monospace}.gg-stage[data-ready="true"]{border-color:rgba(125,246,190,.25);background:rgba(125,246,190,.035)}.gg-provenance{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.28rem}.gg-prov{padding:.42rem;border-radius:8px;background:rgba(255,255,255,.022);border:1px solid rgba(255,255,255,.055);min-width:0}.gg-prov span{display:block;font:600 7px/1 ui-monospace,monospace;opacity:.5}.gg-prov b{display:block;margin-top:.18rem;font:700 9px/1.15 ui-monospace,monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.gg-workbench-actions{display:flex;flex-wrap:wrap;gap:.35rem;margin-top:.5rem}.gg-workbench-actions button{border:1px solid rgba(94,231,255,.2);background:rgba(8,17,29,.88);color:inherit;border-radius:8px;padding:.45rem .52rem;font:700 9px/1 ui-monospace,monospace;cursor:pointer}.gg-workbench-actions button:disabled{opacity:.35;cursor:not-allowed}.gg-workbench-note{margin-top:.45rem;font:600 8px/1.45 ui-monospace,monospace;opacity:.64}.gg-workbench-note strong{color:#ffba7a}.gg-kbd{opacity:.48}@media(max-width:900px){.gg-stage-row{grid-template-columns:repeat(3,minmax(0,1fr))}.gg-provenance{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.gg-stage-row{grid-template-columns:repeat(2,minmax(0,1fr))}.gg-provenance{grid-template-columns:1fr}.gg-workbench-actions button{flex:1 1 auto}}`;document.head.appendChild(s)}
function installUI(){installStyle();const card=$('grammar102Status')?.closest('.grammar102-card');if(!card||$('grammarGlassWorkbench'))return;const ripple=$('changeRippleItem')?.closest('.change-ripple-box');const box=document.createElement('section');box.id='grammarGlassWorkbench';box.className='gg-workbench';box.tabIndex=0;box.setAttribute('aria-label','Grammar Glass workbench health and handoff');box.innerHTML=`<div class="gg-workbench-head"><b>WORKBENCH HEALTH · HANDOFF</b><span class="gg-workbench-state" id="ggWorkbenchState" aria-live="polite">CHECKING</span></div><div class="gg-stage-row" id="ggWorkbenchStages"></div><div class="gg-provenance" id="ggWorkbenchProvenance"></div><div class="gg-workbench-actions"><button id="ggWorkbenchExport">EXPORT HANDOFF</button><button id="ggWorkbenchInspect">INSPECT HANDOFF</button><button id="ggWorkbenchClearStale">CLEAR STALE RIPPLE</button><button id="ggWorkbenchFocus">FOCUS NEXT STEP</button></div><div class="gg-workbench-note" id="ggWorkbenchNote">Viewer-state receipt only. <strong>READY ≠ correctness.</strong> Shortcuts while this panel is focused: <span class="gg-kbd">/ search · Enter trace · 1–4 depth · Esc clear ripple</span>.</div>`;if(ripple)card.insertBefore(box,ripple);else card.appendChild(box);bindUI();dbg.installed=true}
function motionState(){const base=window.__GRAMMAR_GLASS_VISUAL_STATE__||{},b=$('motionToggle'),enabled=!(b&&(b.getAttribute('aria-pressed')==='false'||b.textContent.trim()==='PLAY'));return{...base,motionEnabled:enabled}}
function collect(){const view=window.AXMGrammarGlass102View,state=view?.getState?.()||{},visual=view?.getVisualPlan?.()||null,binding=view?.getBinding?.()||null,rippleApi=window.AXMGrammarGlassChangeRipple,ripple=rippleApi?.getReceipt?.()||null,rippleState=rippleApi?.getState?.()||{},ghost=window.AXMGrammarGlassGhost?.getState?.()||{};return Core.createHandoff({glassLoaded:!!window.__GRAMMAR_GLASS_VISUAL_STATE__?.loaded,documentVisible:!document.hidden,motionState:motionState(),evolutionState:state,visualPlan:visual,overlayBinding:binding,rippleReceipt:ripple,rippleState,ghostState:ghost})}
function repairStale(h){if(h.result!=='HELD_STALE_VIEW_STATE')return h;const api=window.AXMGrammarGlassChangeRipple;if(api?.getReceipt?.()){api.clearRipple();dbg.staleRepairCount++;return collect()}return h}
function refresh(){clearTimeout(refreshTimer);refreshTimer=null;if(!Core)return;let h;try{h=collect();h=repairStale(h)}catch(error){const e=$('ggWorkbenchState');if(e){e.textContent='HELD';e.dataset.state='HELD_STALE_VIEW_STATE'}return}last=h;dbg.result=h.result;dbg.handoffSha256=h.handoffSha256;render(h)}
function later(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refresh,0)}
function render(h){const state=$('ggWorkbenchState');if(state){state.textContent=h.result.replace('WORKBENCH_','').replaceAll('_',' ');state.dataset.state=h.result}const stages=$('ggWorkbenchStages');if(stages)stages.innerHTML=h.health.stages.map(x=>`<div class="gg-stage" data-ready="${x.state==='READY'}"><span>${esc(x.stage.replaceAll('_',' '))}</span><b>${esc(x.state)}</b></div>`).join('');const p=$('ggWorkbenchProvenance');if(p)p.innerHTML=[['GLASS',short(h.bindings.glass?.cycleSha256)],['102-A',short(h.bindings.primary?.sourceCommitSha)],['102-B',short(h.bindings.ghost?.sourceCommitSha)],['COMPARE',short(h.bindings.generationComparisonSha256)]].map(([a,b])=>`<div class="gg-prov"><span>${a}</span><b title="${esc(b)}">${esc(b)}</b></div>`).join('');const exportBtn=$('ggWorkbenchExport'),inspectBtn=$('ggWorkbenchInspect'),clearBtn=$('ggWorkbenchClearStale');if(exportBtn)exportBtn.disabled=!h.bindings.primary;if(inspectBtn)inspectBtn.disabled=false;if(clearBtn)clearBtn.disabled=!window.AXMGrammarGlassChangeRipple?.getReceipt?.();const note=$('ggWorkbenchNote');if(note){const stale=h.health.staleReasons.length?` · repaired stale: ${h.health.staleReasons.join(', ')}`:'';note.innerHTML=`${h.counts.changedLayerCount} changed layers · ${h.counts.availableChangeCount} changed items · ${h.counts.renderedMarkCount} visible marks${stale}. <strong>READY ≠ correctness.</strong> <span class="gg-kbd">/ search · Enter trace · 1–4 depth · Esc clear ripple</span>`}}
function exportHandoff(){refresh();if(!last)return;const blob=new Blob([JSON.stringify(last,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`grammar-glass-handoff-${last.handoffSha256.slice(0,12)}.json`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
function inspect(){refresh();const e=$('inspector');if(e&&last)e.textContent=JSON.stringify({workbenchHandoff:last,truth:'Viewer-state handoff only. Readiness is not correctness, ranking, authority, or causal proof.'},null,2)}
function clearStale(){window.AXMGrammarGlassChangeRipple?.clearRipple?.();later()}
function nextStep(){refresh();if(!last)return;const wait=last.health.stages.find(x=>x.state!=='READY');if(!wait)return $('changeRippleItem')?.focus();const target={LOAD_GLASS:'file',LOAD_102_A:'grammar102PrimaryFile',LOAD_102_B:'grammar102GhostFile',SELECT_LENS:'grammar102Lenses',COMPARE:'grammar102Lenses',TRACE_RIPPLE:'changeRippleItem'}[wait.stage];const el=$(target);el?.focus?.();el?.scrollIntoView?.({block:'nearest',behavior:(window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches)?'auto':'smooth'})}
function scopedKeys(e){if(e.defaultPrevented||e.altKey||e.ctrlKey||e.metaKey)return;const tag=e.target?.tagName;if(['INPUT','SELECT','TEXTAREA'].includes(tag)){if(e.key==='Escape'){e.target.blur();return}return}if(e.key==='/'){e.preventDefault();$('changeRippleSearch')?.focus();return}if(e.key==='Enter'){e.preventDefault();$('changeRippleTrace')?.click();return}if(/^[1-4]$/.test(e.key)){const d=$('changeRippleDepth');if(d){d.value=e.key;d.dispatchEvent(new Event('change',{bubbles:true}))}return}if(e.key==='Escape'){window.AXMGrammarGlassChangeRipple?.clearRipple?.();later()}}
function bindUI(){$('ggWorkbenchExport')?.addEventListener('click',exportHandoff);$('ggWorkbenchInspect')?.addEventListener('click',inspect);$('ggWorkbenchClearStale')?.addEventListener('click',clearStale);$('ggWorkbenchFocus')?.addEventListener('click',nextStep);$('grammarGlassWorkbench')?.addEventListener('keydown',scopedKeys);for(const id of ['file','ghostFile','grammar102PrimaryFile','grammar102GhostFile','changeRippleItem','changeRippleDepth','changeRippleSearch','ghostBlend','grammar102Blend'])$(id)?.addEventListener('change',later);$('motionToggle')?.addEventListener('click',()=>setTimeout(later,0));document.addEventListener('visibilitychange',later);addEventListener('axm:grammar-glass-102-view-changed',later);addEventListener('axm:grammar-glass-ghost-changed',later);for(const id of ['changeRippleTrace','changeRippleClear','grammar102All','grammar102Clear'])$(id)?.addEventListener('click',()=>setTimeout(later,0));document.querySelectorAll('[data-grammar102-lens]').forEach(b=>b.addEventListener('click',()=>setTimeout(later,0)))}
function setup(){if(!Core)return;installUI();refresh()}
window.AXMGrammarGlassWorkbench=Object.freeze({refresh,getHandoff:()=>last,exportHandoff,getState:()=>({...dbg}),contract:Object.freeze({viewerStateOnly:true,exportCreatesEvidence:false,staleStateAutoRepair:true,keyboardShortcutsScoped:true,readinessIsNotCorrectness:true,authority:'NONE'})});setup();
})();
